### ISSUE TITLE
Implement "withLatestFrom" as an extra operator

### ISSUE THREAD

**Issue by jfedyczak** [staltz/xstream#102]
I'm looking for a method to accomplish:

```
--1----2-----3--------4---
----a-----b-----c--d------
       combineLeft
--1?---2a----3b-------4d--
```

I believe that it is called `withLatestFrom` in RxJS. I think it is a really common case in cycle.js development.

For now, I'm using:

```
let withLatestFrom = (a, b) => {
	let c = xs.create()
	let bValue = ''
	b.addListener({
		next: v => { bValue = v },
		error: () => {},
		complete: () => {}
	})
	a.addListener({
		next: v => c.shamefullySendNext([v, bValue]),
		error: () => {},
		complete: () => {}
	})
	return c
}
```

1. Is it possible, to easly compose it from existing operators?
2. Maybe it could be implemented as an extra?

**Comment by staltz** [comment]
Yes, we should make this an extra. We could name it `sampleCombine`. Any other name suggestions?

cc @TylorS @Hypnosphi

**Comment by jfedyczak** [comment]
@staltz Maybe it should accept more than two streams (still triggered by first) - since it emits an array already.

**Comment by TylorS** [comment]
@jfedyczak  It can definitely be composed with current operators

```js
import xs from 'xstream'

function sampleCombine(...streams) {
 return function (sampler) {
   return xs.combine(...streams)
     .map(values => sampler.map(x => [x, ...values]))
     .flatten()
 }
}
```

**Comment by Hypnosphi** [comment]
One thing that `withLatestFrom` as an extra could do is fire events from the main stream even before the first event from the sampler stream. The combinator function should be called with only one argument in those cases.

The recommended `B.map(b => A.map(a => f(a, b)))` replacement returns
```
-------2a----3b-------4d--
```
instead of
```
--1?---2a----3b-------4d--
```

**Comment by staltz** [comment]
I think not, since `?` is unknown. This case is easily solvable with a `startWith`, and is consistent with `combine`, as well as consistent with RxJS `combineLatest` and `withLatestFrom`.

**Comment by xtianjohns** [comment]
I'm working on this extra now and want to make sure we prefer composing with existing operators and with `sampleCombine` as the name.

Additionally, I'm finding myself needing to change @TylorS's composition above in this way:

```js
import xs from 'xstream';

function sampleCombine( ...streams ) {
  return function( sampler ) {
    return xs.combine( ...streams )
      .endWhen( sampler.last() ) // terminate the streams when the sampler ends
      .map( values => sampler.map( x => [ x, ...values ] ) )
      .flatten()
   }
}
```
If I don't do this, that implementation continues forever, regardless of whether or not the sampler terminates. I expect that this is, potentially, an issue with the operator that I am using for a scratchpad, rather than the composition. Regardless, here is my code to produce the infinite stream:
```js
import xs from 'xstream'

function sampleCombine( ...streams ) {
 return function ( sampler ) {
   return xs.combine( ...streams )
     .map( values => sampler.map( x => [ x, ...values ] ) )
     .flatten()
 }
}

const periodicA = xs.periodic( 500 );
const periodicB = xs.periodic( 250 );
const sampler = xs.periodic( 1000 ).take( 5 );
const final = sampleCombine( periodicA, periodicB )( sampler );
// final is an infinite stream

/**
 * And, some blatant coercion to demonstrate why I
 * think this has more to do with .take() than the way
 * the streams are composed.
 */

const blatant = xs.periodic( 1000 ).take( 5 );
blatant.addListener({
  error: () => {},
  complete: () => {
    console.log( 'complete!' );
    blatant.addListener({
      error: () => {},
      complete: () => {},
      next: item => console.log( item )
    });
  },
  next: () => {}
});
// => 'complete!'
// => 5
// => 6
// => 7
// => 8
// => 9
```

**Comment by staltz** [comment]
@xtianjohns thanks for the initiative. I think we should implement all extra operators with OOP and extending the Operator type. This way we have more control over corner cases, and (important) we get to name each producer/operator with a string that will be shown in the devtools.

**Comment by xtianjohns** [comment]
Hey team, I've opened a PR for this and welcome any feedback.
