### ISSUE TITLE
5.3.2 breaks merge()?

### ISSUE THREAD

**Issue by svachalek** [staltz/xstream#103]
I haven't been able to narrow it down further (will try) but there was a breaking change in 5.3.2. A stream that is using merge() operates as expected in 5.3.1 but in 5.3.2 and 5.3.3, output on the first stream (of 3) that is merged will trigger a state where output on the 2nd and 3rd streams does not produce anything on the merge(). (That is, a debug() spy on the input stream is showing activity while one on the merged stream does not.)

**Comment by svachalek** [comment]
(Also note I did try adding replaceError to the merge to see if an exception was being thrown, but it is not triggered.)

**Comment by staltz** [comment]
@svachalek can you try with xstream v5.3.4?

**Comment by svachalek** [comment]
Works for me! Thanks for the quick turnaround.

**Comment by staltz** [comment]
If you want to see why this happened, read #104.
