### ISSUE TITLE
Single page cheat-sheet image.

### ISSUE THREAD

**Issue by travenasty** [staltz/xstream#110]
Here is a PNG cheat-sheet of the marble diagrams, for a compact reference overview to the entire surface area of xstream, plus the currently available /extra imports.

![xstream extra](https://cloud.githubusercontent.com/assets/370488/17834610/34c15564-6706-11e6-9849-071d192f6c4d.png)

**Comment by staltz** [comment]
We could put this in the README

**Comment by staltz** [comment]
Now in the Wiki https://github.com/staltz/xstream/wiki/Cheatsheet
