### ISSUE TITLE
ERROR when using fromEvent in typescript in xstream\extra\fromEvent.d.ts

### ISSUE THREAD

**Issue by ricokahler** [staltz/xstream#119]
```
ERROR in ...\node_modules\xstream\extra\fromEvent.d.ts                                                                      
(1,1): error TS2654: Exported external package typings file cannot contain tripleslash references. Please contact the package author to update the package de
finition.
```

There's a triple slash reference in `fromEvent`. I'm not sure if this package is even meant to used. I just needed document wide `keyup` event streams and I found [this example](https://github.com/cyclejs/cyclejs/blob/master/examples/animated-letters/src/main.js) to contain that use case.

Anyway this should be a simple fix if needed at all.

**Comment by TylorS** [comment]
@staltz This is related to TypeScript 2.x only as far as I know.
