### ISSUE TITLE
Strict typing for stream

### ISSUE THREAD

**Issue by whitecolor** [staltz/xstream#124]
Decided to create an issue for this:
```ts
interface X {
  some: number
}
let stream: Stream<X> = Stream.of({ some: 1, another: 2 }) // no error
let stream2: Stream<X> = Stream.of<X>({ some: 1, another: 2 }) // will error
```

this is more actual in followng case:

```ts
// it will not strictly check each of the streams
merge<X>(
  stream1$, stream2$, stream3$
)
```

Rx typings actually work the same way. Not sure which way is more correct.

**Comment by staltz** [comment]
Are you sure this isn't just a misusage of TypeScript?

**Comment by staltz** [comment]
http://www.typescriptlang.org/play/index.html#src=interface%20X%20%7B%0D%0A%20%20some%3A%20number%0D%0A%7D%0D%0A%0D%0Alet%20arr1%3A%20Array%3CX%3E%20%3D%20Array.from(%5B%7B%20some%3A%201%2C%20another%3A%202%20%7D%5D)%20%2F%2F%20no%20error%0D%0Alet%20arr2%3A%20Array%3CX%3E%20%3D%20Array.from%3CX%3E(%5B%7B%20some%3A%201%2C%20another%3A%202%20%7D%5D)%20%2F%2F%20will%20error

**Comment by whitecolor** [comment]
Yeah I seem, in first case it returns `Stream<any>` which is compatible with `Stream<X>` (though one may not like it).
