### ISSUE TITLE
debounce example (fromDiagram) doesn't work correctly

### ISSUE THREAD

**Issue by whitecolor** [staltz/xstream#127]
This example doesn't work correctly, probably problem with `fromDiagram`

``` js
import fromDiagram from 'xstream/extra/fromDiagram'
import debounce from 'xstream/extra/debounce'

const stream = fromDiagram('--1----2--3--4----5|')
 .compose(debounce(60))

stream.addListener({
  next: i => console.log(i),
  error: err => console.error(err),
  complete: () => console.log('completed')
})
```

I see:

```
> 4
> completed
```

Instead of

```
> 1
> 4
> completed
```

**Comment by xtianjohns** [comment]
Hey @whitecolor, can you check out this [bin](http://www.webpackbin.com/NyfpAfwbz)? I'm seeing the "correct" output (I think) there. I kept pushing back the version number and saw the same behavior, stopped at `5.0.2`.

Any ideas?

**Comment by whitecolor** [comment]
not sure seem to got this result when I was writing throttle operator. I don't use `fromDiagram`
