### ISSUE TITLE
Create an extra partition-like operator

### ISSUE THREAD

**Issue by jerive** [staltz/xstream#130]
I ran into the need of an operator like this one recently: 
```typescript
partition<T>(passes: (next: T) => boolean): [yes: Stream<T>, no: Stream<T>]
```

I tried to work around this, but the only thing that I came out with is manually creating two streams, one filtering the original stream, the other one negating the filter. 
Not really optimal. But it is OK I mean.
Then I realized that xstream operators can only produce one stream (OutSender). And I thought it would be a nice addition to support creating operators that can output several streams (at least as "extra" operators).

What do you think ?

**Comment by staltz** [comment]
Hi @jerive, thank you for taking your time to send us this issue. We appreciate it, however one of the guiding principles for xstream is similar to a principle used in Python: "There should be one-- and preferably only one --obvious way to do it", even considering extra operators. And for that case it would be two usages of `filter`. Using partition would be a shortcut to make that become just one line of code, but consider the costs that would add to beginners who are learning the operators and trying to understand the difference between them. The obvious way here is to use filter twice.
