### ISSUE TITLE
Xstream object not available in the window at http://staltz.com/xstream/

### ISSUE THREAD

**Issue by franciscotln** [staltz/xstream#132]
I'm not able to try xs in the console because it's not loading xstream.min.js script.
Error in the console:
`
Refused to execute script from 'http://raw.githubusercontent.com/staltz/xstream/master/dist/xstream.min.js' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled.
`
and then:
`(index):1127 Uncaught ReferenceError: xstream is not defined` in this expression:
`window.xs = xstream.default;`

**Comment by kt3k** [comment]
same here
![2016-10-31 12 49 04](https://cloud.githubusercontent.com/assets/613956/19843714/897b48f4-9f68-11e6-8f86-e30bc0c50f63.png)

It works in firefox.

**Comment by franciscotln** [comment]
Seems like it doesn't work only in Chrome. As you said: in Firefox it works, Safari as well

**Comment by xtianjohns** [comment]
Hey team, I think this is just related to Github's raw content service. And Chrome simply happens to enable this kind of checking by default unlike some other browsers/services. But the web service doesn't seem to be responding differently to different browsers.

Folks have used [RawGit](http://rawgit.com/) to avoid this problem for awhile. Up to @staltz if he thinks that's a good alternative to linking directly to Github?

**Comment by staltz** [comment]
RawGit sounds ok, let's do that. :)

**Comment by staltz** [comment]
See comment on #186. :)
