### ISSUE TITLE
.debug() assumes output should go to console.log

### ISSUE THREAD

**Issue by SteveALee** [staltz/xstream#133]
In some contexts ```console.log``` might not be the desired output channel or might not even exist. It does exists in the browser and node which covers most contexts, but there are others.

For example I'm looking at using xs in Azure functions where ```context.log()``` is the best output mechanism. Fortunately ```console.log``` does exist in this context but it fills a fairly useless log.

We can add a debug listener to each stream to log to our desired destination but that is clumsy as has to be done for each stream. We also lose the labelorspy symantics

Can we add a way to specify the debug output? A function would be fine.

how about ```xs.setDebugOutput((i) => { ..... }) ```

**Comment by staltz** [comment]
@SteveALee 

`a$.debug(a => context.log(a))` :)

**Comment by SteveALee** [comment]
doh! :) 

Though I have to repeat that every time and is more to type - which is the beauty of .debug compared to RxJS

**Comment by staltz** [comment]
Ok so how about

```js
function f(a) {
  context.log(a);
}

a$.debug(f)
```

**Comment by SteveALee** [comment]
yeah Ok. I'll shut up! I should not work during a boring meeting!

That's better than monkey patching a new func on the prototype!
