### ISSUE TITLE
docs do not mention flattenConcurrently

### ISSUE THREAD

**Issue by SteveALee** [staltz/xstream#134]
I found this in the code and also the HTTP driver docs but it not in the live site or README

**Comment by Widdershin** [comment]
It is documented in the EXTRA_DOCS:

https://github.com/staltz/xstream/blob/master/EXTRA_DOCS.md#flattenConcurrently

Perhaps not visible enough. Maybe we should include the EXTRA_DOCS directly into the README.

**Comment by SteveALee** [comment]
I did look in the extras as that was linked but totally missed the extra docs.

**Comment by staltz** [comment]
Yeah, it's in the extras. Maybe we can add a table of contents for those extras also in the main readme, but this issue itself is not a bug/problem.
