### ISSUE TITLE
Make create api more convinient (like in Rx)

### ISSUE THREAD

**Issue by whitecolor** [staltz/xstream#140]
I think it is reasonable to improve (simplify) `create` interface (to make it compatible with rx).

Current `create` stream api:
```ts
xs.create({
  start: () => {}
  stope: () => {}
})
```
looks original and explicit but not convenient in many cases. Because it forces you to use some context to share objects between start and stop handler and eventually it looks quite clumsy, esp. when you want to be typesafe.

This is the example, instead of this:
```ts
interface Context {
  job: Job
}
xs.create({
  // should also use not arrow function, to have a context
  start: function (this: Context, observer) => {
    ...
    this.job = new Job()
    ..
  }
  stop: function(this: Context) {
    this.job.stop()
  }
})
```

I would rather have this:
```ts
xs.create((observer) => {
    ...
    let job = new Job()
    ...
    return () => job.stop()
})
```

This would be a logical step after such improvement was implemented with `addListener` api.

**Comment by staltz** [comment]
There are two possible strategies here:

1. Move Producer/start/stop architecture entirely to the Observable/subscription architecture
2. Add support for an additional API like `xs.create((observer) => ... return unsubscribe)`

Option (1) is too huge, would probably bring tons of breaking changes. Probably not feasible.

Option (2) is actually already supported, indirectly. We have `fromObservable`. So you can do:

```js
xs.fromObservable(Rx.Observable.create((observer) => {
  // ... 
  return unsubscribe;
}));
```

So, closing this issue.

**Comment by whitecolor** [comment]
The proposal was just about simplifying `xs.create` API, the Option (2) is not viable for this case, one wouldn't want to use Rx dependency just to be able to use such API.

What is the problem with supporting Option (1) along with current Produceer API?

Here
https://github.com/staltz/xstream/blob/master/src/core.ts#L73

producer could be initialized if it is object with `start` and `stop`, or it is a `start` function, that returns `stop` (if there will not be the problem with sync streams that stops just as it starts)

**Comment by staltz** [comment]
How would you set the `_stop` in internalizeProducer? Try to make a PR and you'll see the problems with doing this. Also, it would add more code to core.

**Comment by whitecolor** [comment]
Yes there are problems with sync streams.

**Comment by whitecolor** [comment]
I've made a pull, it should work https://github.com/staltz/xstream/pull/151
