### ISSUE TITLE
flattenSequentially bug

### ISSUE THREAD

**Issue by Alex0007** [staltz/xstream#141]
Check out [this gist](https://gist.github.com/Alex0007/a58171df07da4ffca2abd0d01e70f001)

`3` isn't emitted there

**Comment by whitecolor** [comment]
`flattenSequentially` doesn't work if metastream emits only one single value.

http://www.webpackbin.com/Eyfn0Khxf

**Comment by xtianjohns** [comment]
I'm confident that this behavior is unrelated to the number of streams that are emitted, and has more to do with the source stream (providing the list of streams) ending. Take a look at this [bin](http://www.webpackbin.com/VJFilTrZf) to justify that, it should be very close to the gist and bin above, except I've increased the period between the source stream events.

I've also taken time to debug the producer, and `flattenSequentially` continues to send events downstream from its input streams even if its source stream completes. So I think there are two considerations here:

1. We should probably clean [this](https://github.com/staltz/xstream/blob/master/src/extra/flattenSequentially.ts#L72-L79) up, and remove listeners on the source streams when the source stream ends, if that is how we want this to behave.

2. If that isn't desirable behavior (the source stream canceling the downstream 'flattened' stream), then we need to implement the new correct behavior. Perhaps that means that the source stream may terminate and that simply causes `flattenSequentially` to stop listening for more streams to listen to, but continues to work through the remaining streams in its buffer. This means it will only terminate when any of its observed streams errors or it runs out of streams in its buffer.

Which is the preferred behavior of this operator?

**Comment by staltz** [comment]
The preferred behavior is to mirror `concatAll` from RxJS v5. E.g.: https://github.com/ReactiveX/rxjs/blob/master/spec/operators/concatAll-spec.ts#L10

And corresponding diagram: 

![concatall](https://cloud.githubusercontent.com/assets/90512/20393110/4d26aa78-ace3-11e6-88af-ecc0bd61beb8.png)

I can work on this bug.

**Comment by staltz** [comment]
This is fixed and released in v8.0
