### ISSUE TITLE
Reconfigure Travis badges or branch management

### ISSUE THREAD

**Issue by xtianjohns** [staltz/xstream#147]
Travis supports embedding badges for certain branches. However, it currently displays the status of `master` which is actively developed.

This means that if `master` fails, the latest deployed version of xstream might still be passing. Or it might be failing. And a cursory examination of the badge (it's intended purpose) would indicate only the latter.

Can we update the Travis badge to display only for a `release` branch which tracks the latest released commit, or prevent any development on `xstream/master`?

**Comment by staltz** [comment]
I'm not sure. There's no benefit to running Travis for a released commit, because by definition we only release if all tests pass. On the other hand, `master` reflects not-yet-released code. It may be broken, and should be fixed before being released. `npm run release` will test before anything.

**Comment by xtianjohns** [comment]
Absolutely. I'm not saying to not run Travis for certain commits. Just suggesting that the badge be configured to report passing/failing for only released code. That way, newcomers and non-contributors can use the badge to gauge their confidence in the library.

At the time that I wrote this, the Github's readme indicated that xstream was "failing" on Travis. But the latest release was fine! I may be mistaking the purpose of the badge, but it seems like a scary thing to indicate. If instead the badge is just supposed to let everyone know about `master`, then it's no big deal I suppose.

**Comment by staltz** [comment]
> Just suggesting that the badge be configured to report passing/failing for only released code.

The badge would always be green. In fact, we could make it a static image. Because released code always passes the tests, by definition. :)

**Comment by xtianjohns** [comment]
Yes, you are right. I think what I'm getting at is "that's a nice feature of your library." Just like ComVer and it's small size.

Can you tell me a little bit more about what you want the badge to communicate? I get that you, by convention, don't release failing code. I thought the badge was the proof of that, rather than asking library consumers to take you at your word and replacing the badge with a message "our latest release is stable, just look at my NPM script that I use to release it."

If master is failing, that's what a commit status can tell you. If it is important for you or contributors, you'll see that info where it counts. But I see this badge next to one that tells me how big the library is and how compliant it is with ComVer. And I'm just trying to make the case that that information seems targeted at folks who don't use or contribute to xstream. Maybe it isn't. Do you see things differently? How?

**Comment by staltz** [comment]
Good question about the build badge. It's primarily for the library contributors. I think we could remove it since each commit signals the status anyway, and I also get emails for failing builds.
