### ISSUE TITLE
Documentation for extra operators

### ISSUE THREAD

**Issue by staltz** [staltz/xstream#15]

**Comment by mspoulsen** [comment]
I think I can do this if you still need help :)

**Comment by staltz** [comment]
That'd be lovely! Checkout flattenConcurrently.ts for an example of such documentation.

**Comment by mspoulsen** [comment]
Working on it. Will have it finished today

**Comment by mspoulsen** [comment]
https://gist.github.com/mspoulsen/b144a7fc5caf4e4876e3f965022761a5

Is this ok?

**Comment by staltz** [comment]
Done! Thanks @mspoulsen
