### ISSUE TITLE
Feature: merge() to ignore undefined parameters

### ISSUE THREAD

**Issue by nikoskalogridis** [staltz/xstream#150]
It would be nice if `xs.merge(StreamA, undefined, StreamB)` would work like `merge(StreamA, StreamB)` would and not produce:
```
TypeError: Cannot read property '_add' of undefined
    at MergeProducer._start
```
and
```
Uncaught TypeError: Cannot read property '_remove' of undefined(…)
    MergeProducer._stop
```

errors which are hard to debug on a complex app and do not point at the line of where the problematic merge happened

**Comment by whitecolor** [comment]
`xs.merge(StreamA, undefined || xs.empty(), StreamB)` won't work for you? Allowing undefined is not very type safe and consistent.

**Comment by nikoskalogridis** [comment]
I am not familiar with Typescript and probably using it would avoid the hours I spent trying to find where the problem is. But since we are also targeting native JavaScript wouldn't it be better if the function handled this cases in the first place. That would still work in both Typescript and also native JavaScript.

**Comment by staltz** [comment]
Closed for the same reasons as https://github.com/staltz/xstream/issues/152

**Comment by whitecolor** [comment]
Yeah, use TypeScript)
