### ISSUE TITLE
Introduce argument / state checking for easier debugging

### ISSUE THREAD

**Issue by redhead** [staltz/xstream#152]
When using xstream with cycle.js it is now very hard to debug the code. I found that the library could save a lot of time if the exceptions, and so stacktraces, could be shown as soon as possible to contain the application sources as well and thus understand and navigate to the code-in-error easier.

One of the examples that I found when developing my app was following error:

	Uncaught TypeError: Cannot read property '_add' of undefined(…)
		CombineProducer._start		@	core.js:185
		Stream._add			@	core.js:979
		MapOperator._start		@	core.js:713
		Stream._add			@	core.js:979
		Stream.addListener		@	core.js:1047
		streamSubscribe			@	index.js:39
		(anonymous function)		@	index.js:49
		replicateMany			@	index.js:48
		run				@	index.js:100
		run				@	index.js:36
		(anonymous function)		@	index.ts:11
		__webpack_require__		@	bootstrap b489834…:553
		fn				@	bootstrap b489834…:84
		(anonymous function)		@	bootstrap b489834…:576
		__webpack_require__		@	bootstrap b489834…:553
		(anonymous function)		@	bootstrap b489834…:576
		(anonymous function)		@	bootstrap b489834…:576

Which does not help at all, because there is no file from my project to navigate to.

So I was thinking it would be nice to add at least simple checks of the arguments we provide to the xstream methods / functions.

This particular exception above was caused by passing undefined stream into combine operator. But without knowing which combine operator in what file it was. It is very tedious and time consuming to debug it.

**A simple check of the passed array into CombineProducer constructor could prevent this. (e.g. iterate the array and assert all of the objects are Streams).**

**Comment by nikoskalogridis** [comment]
This could also help with #150 which is the same case but for the MergeProducer.

**Comment by staltz** [comment]
Basically you should be using TypeScript for catching these basic type mismatches. It works wonderfully. I'll just repeat my comment from here: https://github.com/staltz/xstream/issues/58#issuecomment-226754488

*That said*, I think people have complained about this long enough, and you're right. I just opened issue #154. It'll add such warnings only in development mode. Never in production.
