### ISSUE TITLE
Stream.combine().pairwise() sends the same value for prev and next

### ISSUE THREAD

**Issue by appsforartists** [staltz/xstream#153]
[reduction](http://codepen.io/appsforartists/pen/KNyqKr?editors=0010)

```javascript
Stream.combine(a$, b$).compose(pairwise).map(
  ([[prevA, prevB], [nextA, nextB]]) => //...
);
```

doesn't work as expected because `prev` and `next` share a reference.  You can work around this by applying pairwise to each stream before combining them (and adjusting the predicate's signature accordingly):

```javascript
Stream.combine(
  a$.compose(pairwise), 
  b$.compose(pairwise)
).map(
  ([[prevA, nextA], [prevB, nextB]]) => //...
);
```

or adding a map to the chain:

```javascript
Stream.combine(a$, b$).map(pair => [...pair]).map
```

**Comment by staltz** [comment]
I'm aware why this happens. The output of combine is always the same array reference. This is done for performance. In one perspective it's a feature (faster performance), in another perspective it's a bug (this issue). I'm not sure yet what to do but I'm preferring to keep the current behavior.

Curious to hear more thoughts. 

(PS: this issue is basically the same as https://github.com/ReactiveX/rxjs/issues/1686)

**Comment by appsforartists** [comment]
Once I realized it was recycling the reference, I understood what was happening and a workaround became trivial. 

I haven't tested if pairwise also pools references, but it probably should for the same reason. 

Perhaps a note in the combine docs is the way forward:

> **Note:** combine uses the same array instance for each iteration to minimize garbage collection.  If you need to compare emissions over time, either apply pairwise to the streams before passing them to combine, or map the combine output through [].slice. 

pairwise could also test if prev and next are objects and identical references, and warn if they are. 

I can open a PR with that warning and docs note, linking to gists for the workarounds?  It's a similar solution to the MemoryStream/imitate bug.

**Comment by staltz** [comment]
I think a PR to add a note in the docs for combine would be nice.

**Comment by jsdevtom** [comment]
I made [`distinctUntilChangedImmutable`](https://github.com/jsdevtom/distinct-until-changed-immutable) just for this
