### ISSUE TITLE
Pushing to stream from callbacks

### ISSUE THREAD

**Issue by mjleitch** [staltz/xstream#163]
Hey, this is just a question about using xstream from within a custom element. Custom elements have a few lifecycle callbacks (connectedCallback, disconnectedCallback, attributeChangedCallback), from which I'd like to push values to an existing stream from within the element (i.e. this.example$). Obviously, you don't recommend using shamefullySendNext, which seems similar to a Rx.Subject... I could dispatch an event, but I'd prefer pushing direct to a stream. Is there an alternative approach you'd recommend?

**Comment by staltz** [comment]
Hi!

Usually you can do this transformation:

BEFORE
```js
const myStream = xs.create();
// ...
setInterval(() => {
  myStream.shamefullySendNext(Math.random());
}, 100);
```

AFTER
```js
const myStream = xs.create({
  start: (listener) => {
    setInterval(() => {
      listener.next(Math.random());
    , 100);
  },
  stop: () => {},
});
```

And even better:
```diff
 const myStream = xs.create({
-  start: (listener) => {
-    setInterval(() => {
+  start: function (listener) {
+    this.id = setInterval(() => {
       listener.next(Math.random());
     , 100);
   },
-  stop: () => {},
+  stop: function () {
+    clearInterval(this.id);
+  },
 });
```

in order to clean up resources.

- - -

In the worst case, you can use shamefullySendNext. Let me know if this helps.

**Comment by mjleitch** [comment]
Thanks for the recommendation! Love your explanation for why it's called "shamefullySendNext"!
