### ISSUE TITLE
Investigate map+flatten fusion bugs

### ISSUE THREAD

**Issue by staltz** [staltz/xstream#165]
See https://github.com/cyclejs/cyclejs/issues/503

**Comment by TylorS** [comment]
@staltz It is `map` + `flatten` fusion bugs that are occurring  in that issue.

**Comment by staltz** [comment]
Right. My brain fart.

**Comment by staltz** [comment]
Fixed in xstream v10.4 https://www.webpackbin.com/bins/-KgoDZWYbGQ3WRavJLKo
