### ISSUE TITLE
support PromiseLike

### ISSUE THREAD

**Issue by maiermic** [staltz/xstream#166]
I'd like to suggest to support `PromiseLike` as argument of [`fromPromise`](https://github.com/staltz/xstream#fromPromise) or to add a new factory `fromPromiseLike`.

**Comment by xtianjohns** [comment]
Thanks for the issue, @maiermic. Can you describe the `PromiseLike` type or link to an example interface?

`fromPromise` should support "generalized" Promise types and interfaces: anything with a `.then()` method. So if you are using a native Promise it should work, but also if you have constructed your own user-land promise implementation (like bluebird, or Q).

**Comment by maiermic** [comment]
`PromiseLike` is part of TypeScript's [lib/es5.d.ts](https://github.com/Microsoft/TypeScript/blob/d5c1b71429d43e967bc41aece0c2654f4fa259d6/src/lib/es5.d.ts#L1303)

```ts
interface PromiseLike<T> {
    /**
     * Attaches callbacks for the resolution and/or rejection of the Promise.
     * @param onfulfilled The callback to execute when the Promise is resolved.
     * @param onrejected The callback to execute when the Promise is rejected.
     * @returns A Promise for the completion of which ever callback is executed.
     */
    then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): PromiseLike<TResult1 | TResult2>;
}
```

`PromiseLike` is missing the `catch` method of `Promise`. Hence, you can not pass `PromiseLike` to `fromPromise` which expects `Promise`.

**Comment by staltz** [comment]
I think this is doable and wouldn't be a breaking change

**Comment by staltz** [comment]
Done
