### ISSUE TITLE
Is this description about MemoryStream in README.md correct?

### ISSUE THREAD

**Issue by jacobbubu** [staltz/xstream#171]
In the readme.md, that says:
"it has memory. It remembers the most recent (but just one) next event that it sent to its listeners."

But according to https://github.com/staltz/xstream/blob/master/tests/memoryStream.ts#L23, the code shows that the MemoryStream remembered whole event history.

**Comment by staltz** [comment]
Hi @jacobbubu, the MemoryStream remembers the most recent event for listeners that **arrive late**, but for existing attached listeners, it will send all **subsequent** events, obviously.

**Comment by jacobbubu** [comment]
As the test case "https://github.com/staltz/xstream/blob/master/tests/memoryStream.ts#L136" showed, the second listener has been created when the first listener received the complete event. I think the most recent event in MemoryStream would be `['world']`, not ['hello', 'world'].

**Comment by staltz** [comment]
In that specific test case, the stream has restarted.

**Comment by jacobbubu** [comment]
I see. Is this a general design principle for Observables?

**Comment by staltz** [comment]
Observables don't have "addListener"/"removeListener", but RxJS Subjects do, and yes, to some extent this behavior also exists for Subjects. If you subscribe a second time to a ConnectableObservable / RefCounted, its inner Subject will be recreated, and it restarts with the original data source.

**Comment by jacobbubu** [comment]
Many thanks for your detailed answer.
