### ISSUE TITLE
`Stream` can be assigned to `MemoryStream`?

### ISSUE THREAD

**Issue by mightyiam** [staltz/xstream#174]
It seems that TypeScript allows me to assign a `MemoryStream` to a `Stream`.

Is this by design?

**Comment by staltz** [comment]
> It seems that TypeScript allows me to assign a MemoryStream to a Stream. Is this by design?

Yes because every MemoryStream is a valid Stream.

But the title of your question is different:

> `Stream` can be assigned to `MemoryStream`?

No because not every Stream is a valid MemoryStream.

**Comment by mightyiam** [comment]
Thanks.
