### ISSUE TITLE
dropUntil on MemoryStream

### ISSUE THREAD

**Issue by mightyiam** [staltz/xstream#175]
It seems to me that the memory stream does not really drop anything. Perhaps because it is a memory stream and `dropUntil` doesn't change that.

So, when the argument stream emits, all of the remembered values will be immediately emitted.

So, the name `dropUntil` could be misleading? Because in the case of a memory stream, there are no drops?

**Comment by staltz** [comment]
Hmm, I think dropUntil on a memoryStream should indeed drop. So I'd say that's a bug.

**Comment by mightyiam** [comment]
Bugs should be fixed. Please mark it breaking, for me.

So, how do I make a proper "`holdUntil`"?

**Comment by staltz** [comment]
Mark it breaking?

**Comment by mightyiam** [comment]
The fix, I mean. If it is fixed, some of my things break on upgrade.

**Comment by staltz** [comment]
The fact that it is marked as bug does not mean it will not be a breaking change. A bug fix may or may not become a breaking change. In this case it will be a breaking change.

**Comment by mightyiam** [comment]
I know.

**Comment by xtianjohns** [comment]
@mightyiam can you share a bin or a snippet demonstrating your failing behavior? I think I understand your description, but I'm using arbitrary memory streams with `dropUntil` without any of the grouped emission behavior you are. Perhaps I am misunderstanding your use case, though. Here is a snippet, and my [bin](https://www.webpackbin.com/bins/-KfsWVCKGLbxrMDGyc8r).

```ts
import xs from 'xstream';
import dropUntil from 'xstream/extra/dropUntil';

const ticker$ = xs.periodic( 250 ).take( 15 );
const start$ = xs.periodic( 3000 ).take( 1 );

const breaks$ = ticker$.remember().compose( dropUntil( start$ ) );

breaks$.addListener({
  next: x => console.log( x ),
  error: x => console.log( 'error', x ),
  complete: () => console.log( 'done' ),
});
```
Effects:
```
// => 11
// => 12
// => 13
// => 14
// => "done"
```
Perhaps in your case, you've subscribed to your remembered stream _alongside_ your `dropUntil` operator, so emissions have already begun and become 'remembered'? However, when I refactor my example to account for this, I still don't see your behavior.

Specifically, this does not appear to be correct:
> So, when the argument stream emits, **_all of the remembered values will be immediately emitted._**

**Comment by mightyiam** [comment]
Then it is likely that I was just not understanding the timing of my code.
