### ISSUE TITLE
extra operators as named exports

### ISSUE THREAD

**Issue by mightyiam** [staltz/xstream#179]
Instead of 
```ts
import dropRepeats from 'xstream/extra/dropRepeats'
```
We'll have
```ts
import { dropRepeats } from 'xstream'
```

Me like :smirk_cat:.

**Comment by staltz** [comment]
Sorry, not possible because that would add extras to the core, adding a lot of size to the library.

**Comment by mightyiam** [comment]
Tree shaking is not a thing?

**Comment by staltz** [comment]
Tree shaking is always a possibility, but it is optional and assumes you are using some tool for that. We don't want to force everyone to use that tool, and we want to keep xstream foundational and useful even for people who just use browserify.
