### ISSUE TITLE
Support converting Iterables to Streams

### ISSUE THREAD

**Issue by tmpethick** [staltz/xstream#183]
If a generator is used to create an observable (through `most`) which is then converted to a stream with `xs.from` the browser will freeze. I expect this happens because the observers is not unsubscribed from even though the stream is completed so the generator keeps getting called. 

The following snippet recreates the problem:

```js
import xs from "xstream";
import * as most from "most";

const gen = function*() {
  while (1)
    yield 1;
};

xs
  .from(most.from(gen()))
  .take(10)
  .addListener({
    next: i => console.log(i)
  });
```

Originally I wanted to create a stream directly from an iterator but had a similar problem with stopping the producer which was why I turned to observables. If you have any hints on how to implement it without going through observables I would really appreciate it.

**Comment by staltz** [comment]
Hi :)
Thanks for letting us know. Yes, I agree we could support this, probably in the form of an extra Stream factory, in the style of `fromEvent`. The implementation could be inspired by most.js and RxJS.

**Comment by WorldMaker** [comment]
I implemented a very simple [`fromAsyncIterable`](https://github.com/WorldMaker/xstream-extra-factories/blob/master/async-iterable.ts) in my `xstream-extra-factories` library.

**Comment by staltz** [comment]
Instead of adding more and more operators to the extra bucket, I think we need to encourage people to publish their own utilities. Like WorldMaker did
