### ISSUE TITLE
"Awesome" list

### ISSUE THREAD

**Issue by WorldMaker** [staltz/xstream#190]
Given the goal to keep xstream rather lightweight and instead encourage additional operators as outside libraries, might it be a good idea to keep some sort of "Awesome" style list of such outside libraries?

(For instance, I collected a few factory operators I'm finding reuseful between projects in WorldMaker/xstream-extra-factories and an npm package of that name.)

Would you prefer it as Wiki page here to avoid polluting the code repository with PRs, or would you be alright with adding it to the existing documentation in the repository? Or the (silly) "Awesome" list "standard" of just making it its own repository managed by PRs?

**Comment by staltz** [comment]
Hi @WorldMaker I think a Wiki would be good, to help discoverability. The Wiki is already available and can be editted.

**Comment by WorldMaker** [comment]
Sounds good. Appears to me that the Wiki is currently Contributors only; I don't see edit abilities in my account.

**Comment by staltz** [comment]
Try again now

**Comment by WorldMaker** [comment]
I added a wiki page. Hope it will be useful.
