### ISSUE TITLE
Async map with concurrency

### ISSUE THREAD

**Issue by egeozcan** [staltz/xstream#2]
First of all, thank you for the great work. I have a suggestion for the xstream which would enable a lot of use cases: Mapping a stream with a function that returns promises to a stream of the returned values from those promises.

```javascript
stream
    .asyncMap(v => fetch(v), { concurrency: 3 })
    .asyncMap(response => response.json())
```

I can do this by creating a _producer factory_ which accepts a stream and a project but it wouldn't be elegant:

```javascript
//!!naive implementation!! never tested
const queue = require('async/queue');
const xs = require('xstream').default;

function asyncMap(mapTaskToPromise, concurrency) {
    const taskStream = this;
    let taskListener = null;
    let taskQueue = null;
    const producer = {
        start: function (listener) {
            taskQueue = queue(function (task, callback, concurrency) {
                mapTaskToPromise(task)
                    .then(res => {
                        listener.next(res);
                        callback();
                    })
                    .catch(err => callback(err));
            }, 2);
            taskListener = {
                next: (value) => taskQueue.push(value),
                error: (err) => {
                    //listener.error?
                },
                completed: () => {
                    taskQueue.drain = () => {
                        //listener.done?
                    }
                }
            }
            taskStream.addListener(taskListener);
        },
        stop: function () {
            taskQueue.kill();
            taskStream.removeListener(taskListener);
        }
    }
    return xs.create(producer)
}
```

...which can be used like (with the new bind syntax):

```javascript
stream
    ::asyncMap(v => fetch(v), 3)
    ::asyncMap(response => response.json())
```

What do you think? Would something that'd achieve the same effect have a place in the library, i.e. as a method on the stream prototype?

**Comment by staltz** [comment]
Hi @egeozcan thanks for the suggestion and for the interest, but I think this use case is already covered by `map` + `flatten`. Take a look:

```js
stream
  .map(v => xs.fromPromise(fetch(v))
  .flatten()
  .map(response => response.json())
  .addListener( { ... } );
```

Right?

PS: we can reopen the issue if we see that we are actually missing something.

**Comment by egeozcan** [comment]
Ah, missed that. Is there a way to limit the concurrency btw? e.g. when I don't want to make more than X amount of requests concurrently? Or is that something I'd better solve with a wrapper around fetch?

**Comment by staltz** [comment]
We have `flatten` (no concurrency and lossy semantics) and `flattenConcurrently` (fully concurrent, not lossy), but we don't have anything in between. We could consider an optional argument to `flattenConcurrently(max)`, but so far we're trying to see if it's even needed for most people.

If you're looking for hard core customization and diversity of operators, RxJS is the tool.

**Comment by egeozcan** [comment]
I understand. Actually, `flattenConcurrently` works for my use case. I just need to write a proxy function for my promise factories which sets the concurrency like `.map(v => xs.fromPromise(limitConcurrency(3, fetch)(v)))` or something like that. I don't think that you would need to add this to the xstream, too. It does one thing and does it well.

**Comment by staltz** [comment]
@egeozcan Ok, cool
