### ISSUE TITLE
duplicating event on two streams

### ISSUE THREAD

**Issue by anurtayev** [staltz/xstream#200]
Hi,

Form has a Save button. When clicked it supposed to route to another component and save form data. But router$ stream consumes the click event leaving socket$ stream without event to act upon. In the code below saveClick$ only works for router$ but not for socket$.

```javascript
import sampleCombine from 'xstream/extra/sampleCombine'
import parent from '../../../util/parent'
import xs from 'xstream'
import dataRequest from './dataRequest'

export default ({DOM, onion, props$}) => {
  const saveClick$ = DOM
    .select('.MetaNav__Save')
    .events('click')

  return {
    router$: xs.merge(
      DOM.select('.MetaNav__Cancel')
        .events('click')
        .compose(sampleCombine(onion.state$)),
      saveClick$
        .compose(sampleCombine(onion.state$))
      )
      .map(([e, state]) => `/album/${window.btoa(parent(state.id))}`),
    socket$: saveClick$
      .compose(sampleCombine(onion.state$))
      .map(([e, state]) => ({
        messageType: 'graphql',
        message: `mutation {
          setInfo(info: {title: "${document.getElementById('MetaTitle').value}", description: "${document.getElementById('MetaDescription').value}", favorite: ${document.getElementById('MetaFavorite').checked.toString()}}, id: "${state.id}") {
            id
          }
        }`
      }))
      .startWith(dataRequest(props$))
  }
}
```
How can I get two streams powered by same event? `imitate()` seems to be doing the trick but documentation says it exist

> to allow one thing: circular dependency of streams

This is a very basic use case. It feels like I am missing something fundamental. Help is appreciated.

**Comment by FeliciousX** [comment]
this piece of code seems correct to me

but you have to make sure that `socket$` and `router$` is both eventually used and subscribed

**Comment by FeliciousX** [comment]
it is possible ( just a guess ) that your `router$` will make you call and use a separate component? if so, it might happen that the `socket$` is disconnected
