### ISSUE TITLE
something to handle side effect updates?

### ISSUE THREAD

**Issue by graforlock** [staltz/xstream#201]
Working with mutable DOM libraries such as canvas, THREEjs, or game environments, there is a constant need to update reference without returning or modifying the stream, so what one would do is:

```
render$.map(render => {
  render.setSize(window.innerWidth, window.innerHeight);
  return render;
});
```

Which makes it a bit cruel  to do in bigger environments and return all the time.

The way of how some of the libraries like these work, enforce to do something outside of the stream effect, acting on reference, like:

```
render$.do(render => 
  render.setSize(window.innerWidth, window.innerHeight);
);
```

Any thoughts? I know it is not pure, but `.do` exists in some functional languages.

**Comment by geovanisouza92** [comment]
Maybe you could handle this with a Promise. Once fulfilled, it always never execute again.

Usually, I would say to make a write only driver, that is only executed on app bootstrap (Cycle.run). But I'm not sure where to place this `once` operations.

**Comment by staltz** [comment]
Hi @graforlock 

I think you should just add a listener to `render$`:

```javascript
render$.addListener({next: render => {
  render.setSize(window.innerWidth, window.innerHeight);
}});
```
