### ISSUE TITLE
.flatten() not emitting values

### ISSUE THREAD

**Issue by graforlock** [staltz/xstream#205]
I have a xs.merge of clicks from sources coming from different buttons. This gets to DOM sink eventually. What gets rendered depends on the button clicked, for example `forward` or `backward`,  or something else, and so the code is as follows:

```javascript
    const availabilityView$ = availability$$
        .filter(({ type }) => type === widgetSteps.AVAILABILITY)
        .map(logger('coming through.... 1 '))
        .mapTo(
            xs
                .combine(
                    isolateSink(covers$.DOM, 'covers'),
                    isolateSink(dayTimes$.DOM, 'dayTimes')
                )
                .map(availabilityComponent)
        )
        .map(logger('coming through.... 2 '))
        .flatten()
        .map(logger('coming through.... 3 '));
```
```javascript
    return {
        DOM: xs.merge(
            availabilityView$,
            servicesView$,
            submissionView$,
            errorView$
        ),
        HTTP: xs.merge(request$, submit$$)
    };
```

This only works the first time, when i navigate forward and try navigating back, to get to AVAILABILITY step (which is a step one), no value is pushed through past `flatten()`, so I never see logger logging `'coming through.... 3 '`. All of the other merged streams work as expected, but the one that mapsTo to a combined xs stream is faulty as it only works the first time, as described before, after updating the stream value it never emits past `'coming through.... 2 '`.

**Comment by Widdershin** [comment]
It would be easier to diagnose this if you could create a full, minimal reproducer.

My best guess from a quick look is that you might want to use `.map(() => stream)` instead of `.mapTo(stream)`.

```js
  const availabilityView$ = availability$$
        .filter(({ type }) => type === widgetSteps.AVAILABILITY)
        .map(logger('coming through.... 1 '))
        .map(() =>
            xs
                .combine(
                    isolateSink(covers$.DOM, 'covers'),
                    isolateSink(dayTimes$.DOM, 'dayTimes')
                )
                .map(availabilityComponent)
        )
        .map(logger('coming through.... 2 '))
        .flatten()
        .map(logger('coming through.... 3 '));
```

**Comment by graforlock** [comment]
Tried, didn't quite make difference. I will try to create reproducible example later in the day. I am pretty sure its something to do with this inner combine is being used.

**Comment by Widdershin** [comment]
Thanks :)

Also, if you could create a marble diagram with the events you're expecting and what you're actually getting, it would be more clear. Something like the ones in the xstream docs: https://github.com/staltz/xstream/blob/master/EXTRA_DOCS.md#-dropuntilother

**Comment by graforlock** [comment]
I have finally fixed it by, instead of flattening the nested stream, combining it from the start. 

It is somehow less clean, but works:
    
```javascript
const availabilityView$ = xs
    .combine(
        availability$$,
        isolateSink(covers$.DOM, 'covers'),
        isolateSink(dayTimes$.DOM, 'dayTimes')
    )
    .filter(([{ type }]) => type === widgetSteps.AVAILABILITY)
    .map(([, covers, dayTimes]) =>
        xs.of([covers, dayTimes]).map(availability)
    )
    .flatten();
```

This way it emits the value correctly down to DOM `xs.merge`. Forgive me for not having too much time to create reproducible example, will try that tomorrow.

By the way, when using Rx `flatMap` to flatten inner `Rx.Observable` it led to exact same situation where stream wouldn't emit the view.

**Comment by staltz** [comment]
Hi @graforlock. I think this part

```js
    .map(([, covers, dayTimes]) =>
        xs.of([covers, dayTimes]).map(availability)
    )
    .flatten();
```

can be simplified to

```js
    .map(([, covers, dayTimes]) => availability([covers, dayTimes]));
```

**Comment by graforlock** [comment]
Yes, at this moment its probably useful not to use stream, I didn't quite think about refactoring, just wondering why the one works with `.flatten` but not the other for some reason.

**Comment by wyqydsyq** [comment]
```
        .mapTo(
            xs
                .combine(
                    isolateSink(covers$.DOM, 'covers'),
                    isolateSink(dayTimes$.DOM, 'dayTimes')
                )
                .map(availabilityComponent)
        )
        .flatten()
```
Basically says "always map emits to a *new* stream of combined sink DOMs, mapped through `availabilityComponent`, then flattened". So the resulting flattened stream will only emit when your `xs.combine().map()` emits, which in turn will only emit when `covers$.DOM` or `dayTimes$.DOM` emits rather than whenever the source stream (`availability$$`) emits.

The latter (working) example you provided works because the stream coming from `.combine()` will also emit when `availability$$` does, which appears to be your intended behaviour.

So the key thing here is that  your `mapTo` was returning a stream (of streams) that were not emitting when desired, because the input stream you wanted to listen to wasn't included in the `combine`. When your higher level `availability$$` stream was emitting, it was being `mapTo`'d the DOM streams which have not emitted again, so the resulting flattened stream does not emit because none of the streams it flattens did.
