### ISSUE TITLE
Performance reduction

### ISSUE THREAD

**Issue by dfleury** [staltz/xstream#210]
No ideas why but I'm pretty sure that this release 10.9.0 affected my server-side rendering throughput by half.
I did many tests to be confident to affirm that before opening an issue. I have isolated all changes (node version, other dependencies, code changes, etc) until the point of run the application with both versions, 10.8.0 and 10.9.0
This is strange because if it's right, the only code change between this versions which I found was that: https://github.com/staltz/xstream/commit/330aaba1d3c7992bbcf0a54fc9799a7a4a88db94
Can you guys give me your opinion about this hypothesis?

**Comment by staltz** [comment]
Hi @dfleury. I believe it's impossible that such commit made a difference in performance because it's just a TypeScript change which gives the exact same JavaScript as before. If you discover what was your performance culprit, let us know.

**Comment by dfleury** [comment]
Yeah, there is absolutely nothing related to xstream in this case.
Basically, my development cloud service was alternating each deploy between the same 2 units, one fast and another not so much (because it's physically in another machine).
When I thought in this possibility, I deployed the same version twice and got different throughputs.  😒
Sorry, for waste time reading this stupidity.
