### ISSUE TITLE
Add console methods to debug operator

### ISSUE THREAD

**Issue by whitecolor** [staltz/xstream#217]
Add custom console methods for debug output:

Possible APIs:

Custome, flexible:
```ts
.debug({label: 'mystream$', method: 'warn'}) // allows any method
```

more semantic, only some predefined methods
```ts
.debug.warn('mystream$') 
.debug.table('mystream$')
```

Also, there would be useful to have mapping operator for debug output, so this

```ts
debug('mystrem$ name', obj => obj.name)
```

will output only `name` prop, not the whole object.

**Comment by staltz** [comment]
I'm wary about increasing the core size of the library, and this could be built with `compose`-based API easily. As inspiration, https://github.com/cartant/rxjs-spy is good. Sorry for answering so late
