### ISSUE TITLE
Error: fromEvent -> Cannot Find Definition File for 'node'

### ISSUE THREAD

**Issue by jgainfort** [staltz/xstream#223]
When including fromEvent into my .ts file I get the following error when building with webpack.

> node_modules/xstream/extra/fromEvent.d.ts
> (1,23): error TS2688: Cannot find type definition file for 'node'.

I believe its linked to this line
https://github.com/staltz/xstream/blob/7796d10845ca6aa2a85ccc9a9531b21a635dc72a/src/extra/fromEvent.ts#L1

For my build to work I needed to do install 

`@types/node.`

**Comment by staltz** [comment]
Solved as a documentation issue. Thanks for reporting.
