### ISSUE TITLE
Update to TypeScript 2.6.1 with strictFunctionTypes

### ISSUE THREAD

**Issue by whitecolor** [staltz/xstream#231]
[TypeScript 2.6.1 with strictFunctionTypes](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-6.html)

This causes multiple issues in xstream codebase itself, and also it affects typings of different operators (like `flatten`) that can/should be improved/fixed.

**Comment by mightyiam** [comment]
Related to #230.

**Comment by woutervh-** [comment]
Wrote a fix #233

**Comment by webmaster128** [comment]
As I wrote in #233, I think this library can now be used from applications that set strictFunctionTypes = true. So we should close this or clarify that it is only about the test suite.

**Comment by Sinewyk** [comment]
@staltz @whitecolor closed via https://github.com/staltz/xstream/pull/268 or redefine the issue related to types improvement.
