### ISSUE TITLE
How to produce "fresh" stream?

### ISSUE THREAD

**Issue by krainboltgreene** [staltz/xstream#232]
I have a function that looks like this: `fresh(mixed -> mixed): (value) => ...`

For example: `fresh("a") // ""` or `fresh([1, 2, 3]) // []`.

This is valuable in reduce* or map* functions where I need an initial value.

What would be a comparable way to create "fresh" streams and memory streams? I'm thinking `xstream.never()` and `xstream.never().remember()`?

**Comment by wyqydsyq** [comment]
I'm not sure what you mean by a "fresh" stream, it looks like you're attempting to create a new stream from scratch as opposed to using the driver streams you get in `sources` from a cycle app?

You probably want to use [`xs.startWith()`](https://github.com/staltz/xstream#-startwithinitial) or [`xs.create()`](https://github.com/staltz/xstream#-createproducer).
