### ISSUE TITLE
Consider adding merge operator

### ISSUE THREAD

**Issue by gazedash** [staltz/xstream#236]
It may be personal preference, but I think the former version is much cleaner and easier to comprehend.
If it can be an operator, it should be.

Expected behavior:
```
const x = action$ =>
  action$
    .compose(delay(1000))
    .merge(xs.of({ payload: {} }).compose(delay(1500)))
    .map(action => {});
```
Actual behavior:
```
const x = action$ => {
  const inter = action$.compose(delay(1000));
  return xs
    .merge(inter, xs.of({ payload: {} }).compose(delay(1500)))
    .map(action => {});
};
```

**Comment by whitecolor** [comment]
Actually, I would care much more about `.compose(delay(1000))` then about `merge`. Current semantic of `merge(a,b,c)` and `combine(a,b,c)` seem to be ok and more correct. To simplify usage of extra ops I use [xstream-extra](https://github.com/whitecolor/xstream-extra) package.

**Comment by staltz** [comment]
Hi. Thanks for submitting the issue, we appreciate feedback and suggestion improvements.
I think whitecolor has a good point, and indeed there are many utilities that could/should live as an independent package.
