### ISSUE TITLE
subscribe's argument should support Partial<Listener>

### ISSUE THREAD

**Issue by janckerchen** [staltz/xstream#241]
It's very often to subscribe with empty listener, like

```
xs.periodic(1000).subscribe()
```
It's unnecessary to repeat this everytime, in typescript of couse

```
xs.periodic(1000).subscribe({next(){}, error(){}, complete(){}})
```

**Comment by mightyiam** [comment]
You'd never wish to do that, other than debugging, I figure. So maybe it's fine as it is?

**Comment by staltz** [comment]
In JavaScript, `.subscribe({})` should work. In TypeScript, I think it's a bug that it doesn't support `{}`, because the argument should be `Listener`, but under the hood, `subscribe` uses `addListener`, which in TypeScript correctly supports a `Partial<Listener>`.

**Comment by xtianjohns** [comment]
`.subscribe({})` works just fine for me in JS/TS in `11.7`. Should we close?
