### ISSUE TITLE
Can I extends Stream class to  add operators like  .OfType(action)?

### ISSUE THREAD

**Issue by janckerchen** [staltz/xstream#244]
what I want likes this

```ts
action$.ofType(AnyAction)
```
I determine action type by class instead of constant string, so there some logic in `ofType` which `filter` not enough.

Can I extends Stream class  like below and how to fill constructor params?
```ts
class Actions extends Stream<Action> {

  constructor() { super(????) }
  public ofType(action: Action) {
       ....
  }
}
```

**Comment by staltz** [comment]
You can either use compose or extend the Stream class, or monkey patch the method.
