### ISSUE TITLE
Can not flatten `MemoryStream` in typescript

### ISSUE THREAD

**Issue by joemphilips** [staltz/xstream#248]
in xstream version `11.2.0` , when I tried  

```
const test = xs.of(xs.of(null).startWith(null)).flatten();
```

I get the following error in.
```
The 'this' context of type 'Stream<MemoryStream<null>>' is not assignable to method's 'this' of type 'Stream<Stream<null>>'.
  Types of property '_ils' are incompatible.
    Type 'InternalListener<MemoryStream<null>>[]' is not assignable to type 'InternalListener<Stream<null>>[]'.
      Type 'InternalListener<MemoryStream<null>>' is not assignable to type 'InternalListener<Stream<null>>'.
        Type 'Stream<null>' is not assignable to type 'MemoryStream<null>'.
```

I found this when I tried to use HTTPDriver in cyclejs, because it requires to `flatten()` the response.
and it has a [same signature](https://github.com/cyclejs/cyclejs/blob/c2bbccec2bf4990abd9b1220ff1acfd49154f01a/http/src/interfaces.ts#L54)

I workaround by casting it to `Stream<any>` ,  but of course this is not Ideal.
Please tell me if I'm missing something. Thanks!

**Comment by staltz** [comment]
That looks like a duplicate xstream installation. Can you run `npm ls | grep xstream` and see if you have other versions than 11.2.0?

**Comment by joemphilips** [comment]
Thanks for fast response.
by running `yarn list | grep xstream` result was
``` 
│  │  └─ xstream@10.x || 11.x
│  └─ xstream@11.x
│  │  └─ xstream@10.x || 11.x
│  └─ xstream@11.x
│  └─ xstream@11.x
│  └─ xstream@10.x || 11.x
│  │  ├─ xstream@10.9.0
│  │  └─ xstream@10.x
│  └─ xstream@*
│  └─ xstream@^11.2.0
│  └─ xstream@>=10
│  ├─ xstream@^10.8.0
│  └─ xstream@10.9.0
│     └─ xstream@>=10
│  └─ xstream@^11.2.0
│  ├─ xstream@^11.2.0
├─ xstream@11.2.0
```

and the package which rely on only version 10 was
`@cycle/time@0.8.0 -> @cycle/run@1.0.0` and 
`cycle-restart@0.2.3`
I found that latest release of `cycle-restart` has not yet included [this patch](https://github.com/Widdershin/cycle-restart/pull/69/files).
So I'd better use build from the master branch in `cycle-restart` and this should be fixed.
I really don't know what is the best way to use those unpublished version directly from the github, though.

By the way, thanks for this great library!

**Comment by joemphilips** [comment]
Yep. I released the new version of `cycle-restart` for myself and the issue has fixed. So closing now. thanks again!
