### ISSUE TITLE
ReasonML bindings

### ISSUE THREAD

**Issue by italonascimento** [staltz/xstream#251]
Is there already any effort being put on creating bindings for ReasonML?

If not, I'd like to contribute, as I already created some bindings to use on a personal project.

**Comment by staltz** [comment]
Hi! Can it be created in a separate repo? :)

**Comment by italonascimento** [comment]
Yes, it can. And it can be published to npm as an independent package.

**Comment by staltz** [comment]
Good! So I recommend publishing it separately from xstream. Let us know when it's done. :)

**Comment by italonascimento** [comment]
Here it is: https://github.com/italonascimento/reason-xstream

Still need to document everything though, as the usage is slightly different for some operators and factories.

I'll try to publish and start documenting it latter this week. :)
