### ISSUE TITLE
Debounce drops last emitted value if complete emitted too soon

### ISSUE THREAD

**Issue by CarlLeth** [staltz/xstream#257]
Given this stream:
`const stream = fromDiagram('-1----2-|').debounce(50)`,
1 will be emitted, but not 2, because debounce._c calls this.clearInterval() immediately even if a value is waiting to be emitted.

Debounce drops values with the understanding that a fresher value is coming soon after, but that assumption is violated by dropping the last value.  If debounce's purpose is to wait until a rapidly-changing value has settled down, I propose that when it receives complete, things have obviously settled down and it should emit any pending value immediately and then complete.

I am using debounce to prevent the problem where xs.combine(a, b, c, d) emits three (potentially erroneous) intermediate values if a, b, c, and d all change from the same initial event.  xs.combine(a,b,c,d).debounce(0) should fix the problem nicely, but it doesn't, because of the aforementioned issue.  Another option would be to change combine and merge so that synchronous values from multiple of their inputs only trigger one output emission.

**Comment by staltz** [comment]
> [upon source completion] it should emit any pending value immediately and then complete.

I agree this is the right behavior for debounce and we should fix it through a PR. Thanks for reporting @CarlLeth
