### ISSUE TITLE
core.d.ts (55,8): error TS2304: Cannot find name 'Promise'.

### ISSUE THREAD

**Issue by AlexGalays** [staltz/xstream#26]
Hello,

Do I need to do anything other than npm install xstream@2.0.2 for it to pick up its typing dependencies correctly?

I get that error simply by using the library in typescript.

**Comment by TylorS** [comment]
```
typings install -SA es6-shim
```

That's worked for me

**Comment by AlexGalays** [comment]
Doesn't seem to work here :(

**Comment by AlexGalays** [comment]
Ok it's fine now, My tsconfig was not picking up the right typings.
