### ISSUE TITLE
How to handle exceptions in Producer.stop?

### ISSUE THREAD

**Issue by webmaster128** [staltz/xstream#269]
Given this basic producer implementation

```ts
function turnMachineOn() {
  // turn the machine on to start producing
}

function turnMachineOff() {
  // turn the machine off since no production is required anymore
}

const prducer: Producer<number> = {
  start: listener => {
    try {
      turnMachineOn();
    } catch (errorTurningMachineOn) {
       listener.error(`Internal error, machine cannot be turned on: ${errorTurningMachineOn}`)
    }
  },
  stop: () => {
    turnMachineOff(); // where do this exceptions go?
  }
}
```

is there any best practice to handle exceptions or other kind of errors within the stop implementation? Given that stop() is called asynchonously and there is no listener available, those exceptions will end up as some kind of uncatchable "free exceptions" (I'm not an JS engine expert).

**Comment by staltz** [comment]
Hi @webmaster128 I think you can do a try/catch inside the stop, and the catch should handle the error so that the machine is "turned off" in other ways if the standard way of turning off didn't work.
