### ISSUE TITLE
`remember` not working properly

### ISSUE THREAD

**Issue by ntilwalli** [staltz/xstream#27]
Odd issue. When I call `debug` before calling `remember` it works properly but when I don't call `debug` the initial state is not seen by the second listener to a stream. http://www.webpackbin.com/4yza792lZ

Subsequent states (after the initial one) are seen properly, it's the initial state that is missed by the second subscriber

**Comment by staltz** [comment]
@ntilwalli Thanks for reporting, we'll look into it

**Comment by staltz** [comment]
@ntilwalli version 2.1.1 released with a fix for this

**Comment by ntilwalli** [comment]
Excellent!
