### ISSUE TITLE
Indicate that rxjs operators are compatible.

### ISSUE THREAD

**Issue by janat08** [staltz/xstream#272]
I wanted specific throttling and was unaware that rxjs could be chained.

**Comment by staltz** [comment]
Hi @janat08, I didn't know RxJS operators are compatible! :)
I'd be happy to merge a simple PR to change the README to indicate this.

**Comment by janat08** [comment]
I believe you do, as you wrote the article stating such.

**Comment by staltz** [comment]
@janat08 I remember writing that you can easily convert from xstream to RxJS observable, but it surprises me now if the explicit conversion is *not* needed before using the RxJS operator.

**Comment by janat08** [comment]
I suppose you can't go from xs to rxjs then unless you want to pass it through a driver.
