### ISSUE TITLE
support addListener/removeListener in fromEvent

### ISSUE THREAD

**Issue by wclr** [staltz/xstream#284]
What do you think of adding the support for handling common `addListener/removeListener` event emitter targets to `fromEvent`, not just dom nodes?

**Comment by whitecolor** [comment]
and also even `on` and `off` listeners.

@staltz

**Comment by andykais** [comment]
I think this can be closed. I see node listener support here https://github.com/staltz/xstream/blob/6c22580c1d84d69773ee4b0905df44ad464955b3/src/extra/fromEvent.ts#L24

**Comment by staltz** [comment]
Indeed. Thanks!
