### ISSUE TITLE
Each producer gets a name as metadata

### ISSUE THREAD

**Issue by staltz** [staltz/xstream#29]
We may need, for debugging (with a dataflow graph visualizer), a `name: string` field for each producer.

PS: note that `remember` also needs to be visible in the dataflow graph, so its producer also needs a name.

**Comment by cem2ran** [comment]
Not sure if this belongs here or a separate issue. We could encourage the use of named functions to provide intent/metadata for every operator/combinator. This could act as the "default" value for a node's name or provide a description of for instance what a specific "map" node is actually doing when transforming data.

**Comment by staltz** [comment]
Hmm, good idea @cem2ran. It would live in the DevTool, not in xstream directly, but it may be useful after all. Using the stack trace, we can detect in which function was each operator used. This way we can group a subnetwork of nodes in one rectangle if all those nodes (streams) were created in the same function. And if there is only one node in that rectangle (function), then we can just give the of the function to the node.

We anyway need `name: string` which would be in the worst case a human unreadable ID number. We need that for disambiguation when the stream graph diverges or converges.

**Comment by whitecolor** [comment]
> Using the stack trace, we can detect in which function was each operator used. This way we can group a subnetwork of nodes in one rectangle if all those nodes (streams) were created in the same function.

:smile: we are all going to the mars :rocket:

**Comment by staltz** [comment]
This is actually done. :)
