### ISSUE TITLE
26 core operators and factories but I count about 35

### ISSUE THREAD

**Issue by PhilT** [staltz/xstream#297]
I'm probably nitpicking but maybe I'm just confused. Has the number 26 just not been updated or are  some of the functions not counted as core operators or factories?

**Comment by staltz** [comment]
You probably counted all operators + factories + **methods**. Methods aren't operators. E.g.

- addListener
- removeListener
- compose
- shamefullySendNext
- etc

Did I assume correctly?

**Comment by PhilT** [comment]
You did. Thanks for clarifying.
