### ISSUE TITLE
Type signature of remember

### ISSUE THREAD

**Issue by AlexGalays** [staltz/xstream#3]
Shouldn't remember() return a MemoryStream ?

I want to enforce some of my API to return a MemoryStream as it has the exact semantics I require.

**Comment by staltz** [comment]
Hi @AlexGalays :)

Ok, we can change that. It won't propagate when more operators are used on top of that MemoryStream.

**Comment by AlexGalays** [comment]
Hello @staltz :)

Yes, I saw it won't propagate from the code base; any particular reason? Performances / Keeping the code simple?

**Comment by staltz** [comment]
Fixed in 2.1.3
