### ISSUE TITLE
implement extra continueWith (most)

### ISSUE THREAD

**Issue by whitecolor** [staltz/xstream#30]
How about implementing in extras (or maybe not in extras) operator most's [`continueWith`](
https://github.com/cujojs/most/blob/master/docs/api.md#continuewith)

This would allow to know when the stream ends, and commit some actions like in rx's [`finally`](https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/core/operators/finally.md) operator. Can be useful (needed) in proxy subject scenarios to get rid of leak.

**Comment by staltz** [comment]
@whitecolor It seems continueWith is like concat. In that case, we have two extra operators: concat and flattenSequentially (concatMap in RxJS v5). I think that covers a lot of use cases. But I dont know if we have something like finally. How would use you finally? What's the use case? An example?

**Comment by milankinen** [comment]
@whitecolor In `xstream`, memory management of proxies will be done by the library, see #5
