### ISSUE TITLE
Type of _val in MemoryStream

### ISSUE THREAD

**Issue by cem2ran** [staltz/xstream#31]
Wondering if there's a reason why `_val` in `MemoryStream<T>` is not `T` instead of `any`? 
`private _val: T;`

because it can be `undefined/null`?

**Comment by staltz** [comment]
@cem2ran Hmm, it seems it should be `T`. Thanks for pointing out

**Comment by staltz** [comment]
Fixed in 2.1.3, thanks @cem2ran
