### ISSUE TITLE
Include extras in dist

### ISSUE THREAD

**Issue by psirenny** [staltz/xstream#33]
It would be awesome if the extra operators were included in the /dist folder.

**Comment by TylorS** [comment]
Seems like it'd be simple enough to provide a separate build of the extras folder for those that need it.

**Comment by staltz** [comment]
It would have to be

- `dist/xstream.js`
- `dist/xstream.min.js`
- `dist/xstream-with-extra.js`

where the last one would have all the extra operators.

To be honest, `dist` is just for consuming e.g. through npmcdn for usage in JSFiddle or JSBin, which is rarely something to use in production anyway

**Comment by psirenny** [comment]
In that case, is it preferred to build from `/src` when importing from xstream?

**Comment by psirenny** [comment]
Sorry, I was being dense. I didn't notice that an extra folder containing the `.js` operators was built and placed at the root of the package :grin:. I'll leave the issue open in case you want to make the extra operators available to JSFiddle, JSBin, etc.

**Comment by staltz** [comment]
We don't yet intend to do that, so I'll close. Of course it can be reopened.
