### ISSUE TITLE
Export factories from `xstream`

### ISSUE THREAD

**Issue by whitecolor** [staltz/xstream#37]
Allow to do:
```js
import {of, combine, create} from 'xstream'
```

**Comment by staltz** [comment]
What's the benefit of
```js
import {of} from 'xstream'

var stream = of(1, 2, 3)
```
over
```js
import xs from 'xstream'
var stream = xs.of(1, 2, 3)
```

The bottom case has just 1 character more.

**Comment by whitecolor** [comment]
"one" character more? =)
```js
import xs from 'xstream'
var stream = xs.of(1, 2, 3)
//... do it 100 times more
var stream101 = xs.of(1, 2, 3)
```
300 characters more!

It is not about exessive characters but **cleaner code**. I like to have just:
```js
merge(...[
  combine(...),
  of(1, 2,3,)
])
```
rather than:
```js
xs.merge(...[
  xs.combine(...),
  xs.of(1, 2,3,)
])
```
It is the same as with hyperscript:
```js
div([
  h1([....]),
  ul([
    li([...]), li([...])
  ])
])
```
versus:
```js
h('div', [
  h'(h1', [....]),
  h('ul', [
    h('li', [...]), h('li', [...])
  ])
])
```
And this requires not much from `xstream` to have it available.

**Comment by staltz** [comment]
```js
const {of} = xs;
```
Done.
😄 ?

**Comment by whitecolor** [comment]
What's the problem with exporting individual factories?

**Comment by staltz** [comment]
More code, which equals more kB.

**Comment by whitecolor** [comment]
There are 11 factories, assuming that each export will take 15 chars you have about 150 bytes, 0.15kb uncompressed. 

Otherwise why not remove all the exports of hyperscript helpers from `@cycle/dom` to keep it "more lean"?

**Comment by staltz** [comment]
Because `@cycle/dom` is not a foundational library on which we build a ton of other libraries.

**Comment by whitecolor** [comment]
You may have a ton of stuff built on `xstream` in you project, but I have to include only one copy of it per app.

**Comment by staltz** [comment]
Yeah, but that's not always the case. And we want to keep it around 30kB, and there's no space anymore. In fact we need to remove code, not add. I'm considering even moving flattenConcurrently from core to extra. It's simple to just do `const {of} = xs`, so I don't think we will do this feature.

**Comment by whitecolor** [comment]
I'm not sure who are you going to amaze with lib size. Elon Musk brings 50% waste fuel to the orbit, but who cares? He is going to the mars! :rocket:

**Comment by whitecolor** [comment]
btw `mostjs` supports such exports (imports). To me being penny-wise not worth it...

**Comment by staltz** [comment]
Every penny counts, their sum make up a lot. ;)

**Comment by whitecolor** [comment]
Who knew that ES6 exports will lead to such "economy")

**Comment by sveinburne** [comment]
I'm in favor of exporting those factories for code writing productivity. In TS, Webstorm intention will suggest the good imports if it's named imports.
