### ISSUE TITLE
debug with label coverts values to strings

### ISSUE THREAD

**Issue by whitecolor** [staltz/xstream#38]
If use debug without value we will in the console output not converted output for example some object `{a:1}` (can be inspected in the console, etc)

And if use label we will se:
`label: [object object]`

**Comment by staltz** [comment]
What would you expect?

**Comment by whitecolor** [comment]
console (usually) supports multiple arguments, so it will look the same in the console
`label: {a: 1}`
turning the output into one string argument is actual only for some special caess (when only one and usually string arg is supported)

**Comment by whitecolor** [comment]
I do the same way in https://github.com/whitecolor/rx-log

**Comment by staltz** [comment]
Ok, good suggestions

**Comment by staltz** [comment]
Done in 2.6.2
