### ISSUE TITLE
compose should suport arguments

### ISSUE THREAD

**Issue by leiserfg** [staltz/xstream#40]
Current Api
```coffee
Stream.compose = (operator) -> Stream
```
expected Api
```coffee
Stream.compose = (operator, args=[]) -> Stream
```

**Comment by staltz** [comment]
Hi @leiserfg, did you know you can just call an operator factory?

`stream.compose(makeMyOperator(arg1, arg2))`

where
`makeMyOperator: (arg1: A, arg2: B) => ((ins: Stream<T>) => Stream<R>)`
