### ISSUE TITLE
Documentation improvement: imitate

### ISSUE THREAD

**Issue by dmitriid** [staltz/xstream#44]
Currently the documentation regarding `imitate` is confusing to newcomers.

Quoting myself from Gitter :)

> The README is extremely confusing in this respect. "changes the behavior of the current stream, making it re-emit whatever events are emitted by the given other stream"
> 
> Then half of the methods use "imitate" to describe the functionality. And then there's A MimicStream (what?) that is the only one that can have imitate... Because Streams can have it but not MemoryStreams. Whaaaaa....

Suggestions raised on Gitter:

- Add a small example/examples to the documentation section of `imitate`. Something like this (thanks to @TylorS )

```js
const value$ = xs.createMimic()
const component = Component({...sources, value$})
value$.imitate(component.value$)
```

However, the section will also need to clarify the difference between `Rx.Subject` and `.imitate` and possible other uses

- Explain use cases of MemoryStreams vs Streams (thanks to @FeliciousX for suggestion)

**Comment by staltz** [comment]
Fixed. Thanks. I'll release a version soon.
