### ISSUE TITLE
combine breaks when passed two streams that share a parent

### ISSUE THREAD

**Issue by Widdershin** [staltz/xstream#47]
Here is a runnable reproducer:

```js
import assert from 'assert';
import xs from 'xstream';

function Counter (click$) {
  const count$ = click$
    .fold((total) => total + 1, 0)
    .remember();

  return {
    count$,

    countString$: count$.map(count => count.toString())
  };
}

const click$ = xs.create();

const counter = Counter(click$);

const combinedStreams = xs.combine(
  (...vals) => vals,
  counter.count$,
  counter.countString$
);

const expectedValues = [
  [0, '0'],
  [1, '1']
];

combinedStreams.addListener({
  next(vals) {
    console.log('expected:', expectedValues[0], 'actual:', vals);
    assert.deepEqual(expectedValues.shift(), vals);
  },
  error(err) {
    throw err;
  },
  complete() {}
});

click$.shamefullySendNext();
```

```bash
 $ ./node_modules/.bin/babel-node test.js
expected: [ 0, '0' ] actual: [ 0, '0' ]
expected: [ 1, '1' ] actual: [ 1, '0' ]

AssertionError: [ 1, '1' ] deepEqual [ 1, '0' ]
```

We expect to see that the `count$` and `countString$` are equal, but only the `count$` increments on `click$`.

If you pass `countString$` as the first stream to combine, the opposite happens.

This use case is important for @cycle/collection, for combining multiple sinks on each item.

I'm unsure if this is a bug, or if I'm just misunderstanding something fundamental.

**Comment by ntilwalli** [comment]
I think it's just a "glitch" (http://staltz.com/rx-glitches-arent-actually-a-problem.html).  I posted a webpackbin (http://www.webpackbin.com/41pBk6ZN-) which does a "withLatestFrom" approach instead of `combine` and it works.

**Comment by staltz** [comment]
Yeah, it looks like a glitch.

**Comment by Widdershin** [comment]
Not sure that this is legitimately a glitch. If it was a glitch, I would expect to see this output:

```js
[ 0, '0' ]
[ 1, '0' ]
[ 1, '1' ]
[ 2, '1' ] // or whatever
```

The actual output is:

```js
[ 0, '0' ]
[ 1, '0' ]
[ 2, '0'' ]
```

The second stream never emits values (after the first). As such, I think this is related to #60

**Comment by ntilwalli** [comment]
@Widdershin I'm not able to replicate the behavior you describe on webpackbin.  If you look here (I posted your exact code but removed the assert) you'll see the second stream does increment (http://www.webpackbin.com/Nk9ZrTGHb).  Can you post a bin which demonstrates the odd behavior?

**Comment by Widdershin** [comment]
@ntilwalli I can no longer reproduce this issue in the latest version of xstream, so please consider this issue done and dusted. Thanks for your help 😄
