### ISSUE TITLE
MimicStream should pass its listeners to imitated stream

### ISSUE THREAD

**Issue by Hypnosphi** [staltz/xstream#49]
Since 3.0.0, `imitate` works only when placed before listeners (it's an opposite of issue #41 ).

As docs say, `imitate` changes this current MimicStream to imitate the other given stream. In my opinion, this means that no matter when do we add a listener to MimicStream, in the past or in the future, it should listen to the imitated stream (and stop listening to previously imitated stream, if present).

**Comment by staltz** [comment]
You're totally correct, we should do this.

**Comment by staltz** [comment]
Ok, actually I think there is no valid use for calling `imitate` after `addListener`, so this issue becomes deprecated. Read https://github.com/staltz/xstream/commit/8a432b66523924b48adcd974619d0baa98c4f133 for more details.

If we find a very valid use case for `imitate` after `addListener`, we can reopen this issue.

**Comment by Hypnosphi** [comment]
Can we possibly reopen this now to support dynamic graph construction?

**Comment by Hypnosphi** [comment]
An example can be found here https://github.com/cyclejs/examples/blob/88ee42520c2e60c0a7e8ee47b97cdd0e9c73fd9c/advanced-list/src/app.js =)

**Comment by staltz** [comment]
What's the use case?

**Comment by staltz** [comment]
http://www.webpackbin.com/N12gpWq4W

**Comment by TylorS** [comment]
I believe this is covered now already?

**Comment by staltz** [comment]
Yeah
