### ISSUE TITLE
Misleading `imitate` documentation?

### ISSUE THREAD

**Issue by mightyiam** [staltz/xstream#52]
```
import delay from 'xstream/extra/delay'

var secondProxy$ = xs.create();
var first$ = secondProxy$.map(x => x * 10).take(3);
var second$ = first$.map(x => x + 1).startWith(1).compose(delay(100));
secondProxy$.imitate(second$);
```

This is an example from https://github.com/staltz/xstream#-imitatetarget
Further, it says

> "Note, though, that imitate() does not support MemoryStreams. If we would attempt to imitate a MemoryStream in a circular dependency, we would either get a race condition (where the symptom would be "nothing happens") or an infinite cyclic emission of values. It's useful to think about MemoryStreams as cells in a spreadsheet. It doesn't make any sense to define a spreadsheet cell A1 with a formula that depends on B1 and cell B1 defined with a formula that depends on A1."

Yet, in the example, as far as I can tell, `imitate` receives a MemoryStream. `second$` results from `.startWith`. In [the docs for `.startwith`](https://github.com/staltz/xstream#startWith) it is written that `startWith` returns a MemoryStream.

**Comment by staltz** [comment]
`.compose(delay(100))` returns a Stream, not a MemoryStream, so `second$` is a Stream given to imitate().
