### ISSUE TITLE
imitate doesn't work if placed after addListener

### ISSUE THREAD

**Issue by whitecolor** [staltz/xstream#54]
Here `imitate` call comes after `addListener`, and it doesn't start.

http://www.webpackbin.com/N12gpWq4W

I'm not sure if this is unexpected, but still worth noticing and checking.

**Comment by Hypnosphi** [comment]
it's a duplicate https://github.com/staltz/xstream/issues/49

**Comment by whitecolor** [comment]
Didn't see it, but it is still exists.

**Comment by staltz** [comment]
Yeah let's use that one.
