### ISSUE TITLE
Strange behavior

### ISSUE THREAD

**Issue by mspoulsen** [staltz/xstream#59]
Surely, there must be some kind of bug here:

http://www.webpackbin.com/417uJTnE-

My log driver is stealing my data. :) Happens with infinite streams only and if I move DOM below LOG

**Comment by Hypnosphi** [comment]
You must `remember` if you want multiple listeners to acces the initial stream value

**Comment by mspoulsen** [comment]
Really?? I thought the framework would figure that out. The component doesn't know it has multiple listeners....but ok.

**Comment by Hypnosphi** [comment]
Your main function is the one who knows: it makes two sinks depend on the same non-memory stream

**Comment by Hypnosphi** [comment]
And it's usually better to have `DOM` sink as MemoryStream anyway

**Comment by mspoulsen** [comment]
I see! So, how do explain this: http://www.webpackbin.com/4J2ow0nEW  :smile:

**Comment by Hypnosphi** [comment]
`xs.of('foo')` completes before second listener attaches, so it's stopped and then reinitialized
`xs.periodic()` is asynchronous

**Comment by mspoulsen** [comment]
Excellent! I am sorry if I ask too many questions, but:

1. Why is xs.of('foo') re-initialized?
2. Why does xs.periodic() being asynchronous mean that it is logged twice?

I think my problem is that I often use exactly these two operators to test my data streams and they seem like poor choices since they apparently behave quite differently than most of my real data streams (usually a never ending stream with initial state like fooInfinite$). Maybe I should make factory for fooInfinite$ :)

I have never had as much fun programming as with FRP but I must say that there a quite a few gotchas when coming from traditional imperative programming :open_mouth: 

Thanks again :+1:

**Comment by Hypnosphi** [comment]
1. Because when stream completes, it loses all its listeners. So when the second listener attaches, total listener count goes from 0 to 1 again, which triggers initialization.

2. Because the first value gets emitted when all the listeners are already attached. You can try `xs.merge(xs.periodic(), xs.of('foo'))` and it will duplicate all but the first value (which is synchronous)

**Comment by mspoulsen** [comment]
Ahhh...ok, I get it! Totally makes sense now! Learned a lot! Thanks!
