### ISSUE TITLE
TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by krainboltgreene** [staltz/xstream#64]
So if a is undefined, we get an issue: https://github.com/staltz/xstream/blob/master/src/core.ts#L932-L941

The error message doesn't actually tell the user what's wrong with the situation though.

**Comment by Hypnosphi** [comment]
how did `this._ils` become undefined in your case?

**Comment by krainboltgreene** [comment]
It's because I got cheeky and assumed the functions could be passed as values.

``` javascript
twitterClient.on('data', listener.next)
```

**Comment by Hypnosphi** [comment]
they could: `twitterClient.on('data', listener.next.bind(listener))`

**Comment by krainboltgreene** [comment]
Oh, I know how to solve it. But the error message could be more useful. If you expect this value, it should report as such:

"Error: Expected to be bound to a listener object, make sure you're not passing the next/error function as a value"

**Comment by Hypnosphi** [comment]
Then it's a duplicate: https://github.com/staltz/xstream/issues/58

**Comment by staltz** [comment]
Ok, it's included in the discussion in #58. We won't build error messages like this, but I have been considering a debug mode for xstream where we don't care about kB size and can add many warnings and errors, so this issue may resurrect if we need to remember this use case. Thanks.
