### ISSUE TITLE
fromEvent on node.js events

### ISSUE THREAD

**Issue by jfedyczak** [staltz/xstream#65]
I'm trying to migrate from most.js. Is it possible to use `fromEvent` on node.js events? I'm trying to pass `EventEmitter` as a source but with no luck...

**Comment by Hypnosphi** [comment]
As stated in [docs](https://github.com/staltz/xstream/blob/master/EXTRA_DOCS.md#fromEvent), `fromEvent` is suited for DOM events. It uses `.addEventListener` internally. `fromNodeEvent` could be implemented like this:
```js
function fromNodeEvent(emitter, event) {
  let callback;
  return xs.create({
    start(listener) {
      callback = value => listener.next(value);
      emitter.addListener(event, callback);
    },
    stop() {
      emitter.removeListener(event, callback);
    }
  });
}
```

**Comment by jfedyczak** [comment]
Are you planning on adding such method? It is present in `most.js` and in `RxJS`. I would provide a PR, but my TypeScript is not that fluent...

**Comment by staltz** [comment]
I think we could do this, since fromEvent is an extra, and size is not a concern, but parity with RxJS and most.js is a benefit.

**Comment by jfedyczak** [comment]
Thank you for the fix, but I'm trying to test this and I believe there's a problem with emitting events with more than one argument as in:

	var fromEvent = require('xstream/extra/fromEvent').default
	var http = require('http')

	var srv = http.createServer()

	fromEvent(srv, 'request')
	.addListener({
	  next: function(req, res) { // <-- problem here
		  // res is undefined
		  res.end(req.url)
	  },
	  error: function(err) { console.error(err) },
	  complete: function() { console.log('completed') },
	})

	srv.listen(3002)

Possible solution would be emitting an array with all the args or passing all the args...

**Comment by staltz** [comment]
Yeah, it would have to be an array or an object.

**Comment by xtianjohns** [comment]
I sympathize with the use case there, @jfedyczak. I think implementations in other libraries handle this issue with selector support, which allows users to declare how to map the arguments from the emitter into the stream.

I'd be happy to take a stab at that, but I think it deserves a separate issue and maybe a discussion about how that approach fits in with the larger goals of xstream.
