### ISSUE TITLE
fromObservable() / toObservable()

### ISSUE THREAD

**Issue by staltz** [staltz/xstream#7]
The ES Observable https://github.com/zenparsing/es-observable/, using perhaps this https://www.npmjs.com/package/symbol-observable

Then send PR to https://github.com/sindresorhus/awesome-observables

**Comment by egeozcan** [comment]
Actually a MemoryStream can be seen as an observable. My wild guess is that aside from potential naming issues, xstream is already 90% API compatible to observables.

**Comment by staltz** [comment]
This issue is about supporting the official symbol to get an ES Observable

**Comment by egeozcan** [comment]
Got it. Then one could also do Observable.from(stream) too. Which would be nice for playing well with the rest of the js ecosystem.

**Comment by expelledboy** [comment]
@staltz can this be reviewed?

A side note, you should checkout the ava test framework which has support for testing observables!

```javascript
test(t => {
    t.plan(3);
    return Observable.of(1, 2, 3, 4, 5, 6)
        .filter(n => {
            // only even numbers
            return n % 2 === 0;
        })
        .map(() => t.pass());
});
```

**Comment by TylorS** [comment]
`fromObservable` is definitely covered now, and Symbol.observable is now present. Does that cover this? Or are you imagining a `toObservable` returning a different class with a constructor accepting a `subscriberFn`?

**Comment by staltz** [comment]
You're right, we don't need toObservable. This is done :)
