### ISSUE TITLE
Replace Producer concept with (ES or RxJS) Observable

### ISSUE THREAD

**Issue by staltz** [staltz/xstream#72]
Xstream is hot streams only, but in rare cases we need cold streams. @TylorS had experienced this hard limitation in a convincing use case. We were discussing what alternative solutions do we have, and we landed on one very interesting possible solution: *to replace Producers in xstream with typical Observables*.

That would mean dropping the `{start, stop}` API for a familiar `subscribe` + `subscription.unsubscribe` API. It means everywhere where we expect a Producer, we would expect a cold Observable, e.g. `xs.create(observable)`, where `observable` is an object with a `subscribe(observer)` function.

This would enable also very interesting interop with RxJS, because we could do `xs.create(Rx.Observable.of(1,2,3))` for instance. The only requirement that we have from `obs` in `xs.create(obs)` would be that it's an object with `subscribe(observer)` function. Alternatively, we could also support the API `xs.create(subscribe)` where `subscribe` is the function `subscribe(observer)`. So the type signature for `create` would be:

```js
type Subscribe<T> = (observer: Observer<T>) => Subscription;

interface Observable<T> {
  subscribe: Subscribe<T>;
}

function create<T>(o: Observable<T> | Subscribe): Stream<T>;
```

In essence, `xs.create` would behave like a multicast in RxJS, with the additional effect of converting from cold world to hot world **permanently**, since we don't have a conversion path from xs.Stream => Observable.

This is for now very experimental, @TylorS will give it a try. He's going to build it as an experiment in a PR. It would affect a lot of the current infrastructure in xstream, and would mean a breaking change, **but** for most xstream/Cycle.js users there wouldn't be any noticeable changes if they are using streams created in drivers and just using operators inside `main()`.

Anyone else wants to give their opinion about this? Any foreseeable problems that I haven't mentioned? @Widdershin @Hypnosphi @laszlokorte @blesh

**Comment by Widdershin** [comment]
> @TylorS had experienced this hard limitation in a convincing use case.

I know Tylor explained this once before, but what exactly is the use case we're talking about?

I would also love to see a failing test for the current version of xstream that shows the behavior we want to achieve.

**Comment by staltz** [comment]
> I would also love to see a failing test for the current version of xstream that shows the behavior we want to achieve. 

Well, here's a naive one: `xs.create(observable)` fails because `observable` doesn't `start` nor `stop`. What this issue means for cold/hot in xstream is that xstream would still be hot-only, but you could use another cold-by-default library like most or RxJS if you want cold.

**Comment by dmitriid** [comment]
I'll leave my (pseudo-)philosophical two cents.

If xstream covers 80-90% of use cases as it exists now (and I think it does), it's a very good time to start looking at the other 10-20% of cases. So go for it based on this alone :) Especially since it's not a theoretical thing, but there exists a proven real-world use case.

Other considerations:

- interop is good. Seamless interop is even better. Even if it's just a one-way Rx cold observable -> xstream hot observable (for now?).
- choice is good. Especially if it doesn't significantly increase "API area". That is, if it doesn't blow up the API from 26 operators to 126 operators and doesn't introduce weird friction points and impendance mismatches.
- familiar is good. For people coming from other libararies/frameworks familiar APIs may help understand things better (but this is a very minor point)

**Comment by Hypnosphi** [comment]
I've reproduced the usecase mentioned and it works normally
https://github.com/staltz/xstream/pull/60#issuecomment-227421302

**Comment by blesh** [comment]
I think this is a good idea, because it would enable interop with more libraries than just RxJS. Most streams, or even a Redux store could be used as a producer.

**Comment by staltz** [comment]
@gaearon ⬆️ here's a good reason why it'd be nice to augment the Redux API from

```typescript
type Listener = () => void;
subscribe(listener: Listener)
```

to

```typescript
type ListenerFunction = () => void;

interface ListenerObserver {
  next: (x: any) => void;
  error: (err: any) => void;
  complete: () => void;
}

type Listener = ListenerFunction | ListenerObserver;

subscribe(listener: Listener)
```

Which would be non-breaking change, and would make Redux stores more Observablesque, composable with either RxJS or xstream.

**Comment by blesh** [comment]
@staltz you don't really even have to... `Rx.Observable.from(reduxStore)` actually works. Redux stores implement `[Symbol.observable]()`.

**Comment by staltz** [comment]
I think this is not going to happen, so closing...

**Comment by netgusto** [comment]
> I think this is not going to happen, so closing...

Is there any way to `next` an observable then ?
