### ISSUE TITLE
Unexpected behaviour from startWith combined with flatMap

### ISSUE THREAD

**Issue by Steelfish** [staltz/xstream#78]
Earlier today I came across this odd interaction when writing a cycle component. It seems that a flatmapped stream with a startWith value will only emit the starting value to one listener. For a Cycle component, which relies on some initial value for mapping to the DOM source from my understanding, this is not ideal. I've created a sample of the behaviour in a webpackbin: http://www.webpackbin.com/VJ9G6zJDb

What it essentially boils down to is the following: 
```
const streamWrapper = xs.of({
    stream: xs.of("").compose(delay(0))
    .mapTo("This is received by all.")
    .startWith("This is received by one.")
});
const stream = streamWrapper.map(wrapper => wrapper.stream).flatten();
```
When given a stream that does not immediately emit any events (hence delay(0)), the value from startWith is only emitted to a single listener on the flatmapped stream. From there on out, all listeners receive the events. Without the flatMap operator, both listeners receive the initial value. (Stream 2 in the webpackbin.) When a delay operator is added to the flatMapped stream, both listeners receive the initial value as well. (Stream 3 in the webpackbin).

I expected both listeners to receive the initial value, is this correct or am I missing something?

**Comment by staltz** [comment]
When "listeners arrive too late", you need a MemoryStream. `startWith` already returns a MemoryStream, but after composing with map+flatten, `stream` is not a MemoryStream. So add `remember` after `flatten()`. Read the "overview" in README for more info. 

If it doesn't work, let me know.
