### ISSUE TITLE
Improve Stream.merge types

### ISSUE THREAD

**Issue by tp** [staltz/xstream#80]
When using `Stream.merge` I found that I had to manually define the types since TS could not infer them with the current signature, which makes it of course error prone:

```ts
const merged = xs.Stream.merge<A | B>(a, b);
```

From what I have seen so far to get variadic-ish generically typed arguments supported, we could use a function signature like this:
```ts
static merge<T1, T2>(s1: Stream<T1>, s2: Stream<T2>): Stream<T1 | T2>;
static merge<T1, T2, T3>(s1: Stream<T1>, s2: Stream<T2>, s3: Stream<T3>): Stream<T1 | T2 | T3>;
[...]
```

(I am pretty sure this works in .d.ts files, not sure how to annotate a function written directly in TS code with this though)

Code like this is often generated for up to 20 or 30 arguments, and then provides full type safety.

**Comment by Hypnosphi** [comment]
what is `Stream.merge`? Since 4.0.0, there's only `xs.merge`.

Anyway, why do you need to merge streams of different types?

**Comment by staltz** [comment]
I agree with this suggestion, seems easy to do and we should do it.

**Comment by xtianjohns** [comment]
I can jump on this if no one objects. Two questions:

1. How far should we go when overloading the method? Rx goes to [six](https://github.com/ReactiveX/rxjs/blob/master/src/operator/merge.ts#L77-L92), but I feel like I've seen them do more elsewhere.

2. Should we one-line those overloads or try to keep them to the width throughout the rest of the project?

**Comment by staltz** [comment]
@xtianjohns good! We should do like Combine has: https://github.com/staltz/xstream/blob/master/src/core.ts#L135
