### ISSUE TITLE
Listener.next accepts only one argument

### ISSUE THREAD

**Issue by perrin4869** [staltz/xstream#81]
This could lead to some rather clunky code in `cycle.js` drivers like `socket.io`, where events can accept multiple arguments. The `spread` operator can probably help here.

**Comment by Hypnosphi** [comment]
Do you want streams to hold multiple values?

**Comment by perrin4869** [comment]
hm... when you put it that way... I guess it's not possible?

**Comment by staltz** [comment]
You need to adapt the API of libraries like Socket.io, xstream's addListener doesn't accept just any type of functions. You would adapt it like:

```js
xs.create((listener) => {
  socket.on('private message', function (from, msg) {
    listener.next({from: from, msg: msg});
  });
  // ...
});
```

It's anyway a better idea to have one argument, not many, because it's like this also in the ES Observable spec, in RxJS, in most.js, etc.

**Comment by perrin4869** [comment]
I made a fork of `cycle-socket.io`, and tried to make a somewhat more general solution to the problem. I sent a PR too.
Do you have any better suggestions?
https://github.com/perrin4869/cycle-socket.io/blob/xstream/src/index.js

**Comment by perrin4869** [comment]
```js
               this.eventListener = (message) => {
                    if (args.length === 1) {
                        listener.next(args[0]);
                    } else {
                        listener.next(args);
                    }
                };

                socket.on(eventName, this.eventListener);
```

**Comment by staltz** [comment]
Perhaps 
```js
socket.on(eventName, (...args) => listener.next(args));
```
?

**Comment by perrin4869** [comment]
oh crap, I made a mistake on the `eventListener` arg, it's supposed to be `...args` indeed.
Yeah, that, only in the case where `args.length === 1` I just send `args[0]`... somewhat of a hack though, I think it makes sense

**Comment by perrin4869** [comment]
I was thinking that maybe the best solution might be a `multiargs` option which defaults to false, but when true, will pass all the arguments to the string as an array. Kind of how `bluebird` handles things with promises, for example, `Promise.fromCallback` accepts an optional `multiargs` flag.

```js
if (opts.multiargs) {
  this.eventListener = (...args) => listener.next(args);
} else {
  this.eventListener = arg => listener.next(arg);
}
```
