### ISSUE TITLE
Events with more than one argument

### ISSUE THREAD

**Issue by jfedyczak** [staltz/xstream#84]
As per suggestion of @xtianjohns I'm creating new issue conected with [this issue](https://github.com/staltz/xstream/issues/65). There's a problem with emitting events with more than one argument as in:

	var fromEvent = require('xstream/extra/fromEvent').default
	var http = require('http')

	var srv = http.createServer()

	fromEvent(srv, 'request')
	.addListener({
	  next: function(req, res) { // <-- problem here
		  // res is undefined
		  res.end(req.url)
	  },
	  error: function(err) { console.error(err) },
	  complete: function() { console.log('completed') },
	})

	srv.listen(3002)

Possible solution would be emitting an array with all the args or passing all the args...

**Comment by TylorS** [comment]
@jfedyczak I don't think Server's are really a use case for xstream, as it's designed for (and only for) Cycle.js

**Comment by jfedyczak** [comment]
@TylorS Well, it is just an example of use with EventEmmiter event which is now supported by xstream as an extra...

**Comment by staltz** [comment]
xstream listener functions, just like ES Observable or RxJS, will *always* take just one argument. If there is an API that deviates from that, then we need to convert multiple args to an array or an object that collects them. I'd be happy to get a PR for this for `fromEvent`.

**Comment by sculeb** [comment]
It would help if the fromEvent had selector support like rxjs. Then one could map multiple arguments of the event to an object or just use the argument he needs or w/e.

usecase:

`// mqtt-connection`
`client.subscribe(topic);`
`fromEvent(client, 'message', (topic, message) => message.toString())`
`.addListener({`
` next: val => console.log(val),`
` error: err => console.log(err),`
` completed: () => console.log('done')`
`});`

**Comment by xtianjohns** [comment]
I'm excited to take a stab at supporting these. @jfedyczak, I worked on the `fromEvent` support for Event Emitters, and you're right that the current implementation lacks the same features as some other stream libraries. One concern was that supporting selectors using the same signature as some other libraries would be a breaking change. Specifically, the third argument (used for DOM event support) would need to be moved.

I can get a PR in for this, but if folks have concerns about a potentially breaking change for the extra and want that to be tackled in a particular way, let's discuss. My instincts are to move the (currently) third argument into an optional fourth argument, which would be a hash of options.

Does this seem reasonable?

**Comment by staltz** [comment]
I find `selector?: SelectorFn, options?: EventOptions` problematic since it gives special treatment to the selector, and it makes the total count of parameters be 4.
How about putting the selector inside the options?

**Comment by xtianjohns** [comment]
Yeah, four parameters is a lot. I don't really like the method-on-options approach, but I can't express why. It just feels fishy to me.

So, that signature (in my example) is what Rx implements. But `most.js`'s arguments are the same as xstream's current implementation. However, it aggregates all of the arguments into an array passed to the listener, only if there are multiple arguments. This might be harder for us to implement in the extra, but it'd enforce that stream modifications take place in `map()`, which is probably where they should belong.

Which way are folks leaning?

**Comment by staltz** [comment]
> But most.js's arguments are the same as xstream's current implementation. However, it aggregates all of the arguments into an array passed to the listener, only if there are multiple arguments. This might be harder for us to implement in the extra, but it'd enforce that stream modifications take place in map(), which is probably where they should belong.

most.js's way seems the best in my opinion. I don't think it'd be that hard to implement.

**Comment by xtianjohns** [comment]
Cool - I'll take that approach then. Thanks!

**Comment by staltz** [comment]
Done in v5.3.0
