### ISSUE TITLE
debug, map, flatten bug

### ISSUE THREAD

**Issue by staltz** [staltz/xstream#91]
http://jsbin.com/hihuvuqupo/edit?html,js,console

**Comment by ShayMatasaro** [comment]
@staltz 
this jsbin as well as the ones listed on the main cycle site in the documentation section all fail with : 
ReferenceError: xstream is not defined

**Comment by mz3** [comment]
I have a stream that does not emit anything unless there is a .debug(noop) tacked on the end. Do you think it is related, or should I post another issue with detail?

**Comment by staltz** [comment]
Just open another issue. We can't be sure yet it is the same bug.

**Comment by staltz** [comment]
This should be fixed now in v6.0
