### ISSUE TITLE
combine() debugging

### ISSUE THREAD

**Issue by svachalek** [staltz/xstream#92]
I really like the direction this library has been moving, it's really become very streamlined and intuitive. However as a stream/reactive newcomer I confess there's still one thing I find really difficult to deal with: a jammed combine(). 

I can get behind the idea that combine() should wait for values on all incoming streams before emitting anything, but in practice there always seems to be some case that will cause one of the inputs to stop producing and then the entire program comes to a screeching halt. I've learned that this means a combine(), somewhere, is blocked on an input but that can mean adding debug spies to practically every stream in the system to figure out which combine it is, and then which input, and then possibly on to another level of combine.

I've been thinking, the original combine() method had a map() built into it that got removed. But the current version essentially still has a filter() in it as well, that blocks any incomplete array from being emitted. Making that filter() explicit would make problems like this a lot easier to find, as you could turn it off and have a mostly running program that should easily reveal what value is not being set. Or you could replace it with a different filter that could time out, or register itself on a list of filters that have or have not passed a value, etc.

Anyway just a suggestion, wondering if anyone else finds this a common problem.

**Comment by staltz** [comment]
@svachalek You can always just `startWith` each of the member streams.

```diff
-var c$ = xs.combine(a$, b$);
+var c$ = xs.combine(a$.startWith(null), b$.startWith(null));
```

And then you'll never seen "jamming" happening, but you will see null values.

**Comment by Hypnosphi** [comment]
A helper for that would look like

```js
function combineProgressive(streams) {
  return xs.combine(streams.map(stream => stream.startWith(null)));
}
```

this makes the result a MemoryStream, but I don't think it's bad: `combine` has clear "value over time" semantics anyway (it uses current values of argument streams). Maybe it should even always return MemoryStream like `startWith` and `fold` do.

**Comment by staltz** [comment]
We can think about that @Hypnosphi. We can look for potential cases of combine that should return `Stream` only, if that exists.
