### ISSUE TITLE
MemoryStream does not multicast properly, repeatedly triggers upstream calls

### ISSUE THREAD

**Issue by ntilwalli** [staltz/xstream#93]
Since it's automatically hot, I expect a `MemoryStream` to allow multicasting without re-triggering the upstream closure chain like a cold stream would, but that's not the behavior I am seeing.  Using v5.3.2 the upstream chain seems to be called for each downstream listener: http://www.webpackbin.com/NykQCF-_-

When testing with Rx 4 and `shareReplay`, I get the behavior I would expect: http://www.webpackbin.com/41l_Yaxu-

Isn't `remember()` supposed to be equivalent of `shareReplay(1)`?

**Comment by ntilwalli** [comment]
@xgrommx posted that `xstream` has the same behavior as  Rx 5: http://www.webpackbin.com/4ku5pag_-

**Comment by staltz** [comment]
Fixed in v7.0
