### ISSUE TITLE
How to test xstream?

### ISSUE THREAD

**Issue by maiermic** [staltz/xstream#94]
Coming from RxJS: Is there anything similar to [`Rx.TestScheduler`](https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/testing/testscheduler.md)? The concept of scheduling in virtual time seems like a must-have to me. There is even a great article about [Testing your Rx application](https://github.com/Reactive-Extensions/RxJS/blob/master/doc/gettingstarted/testing.md). I'd like to see some documentation about *how to test xstream* here as well.

**Comment by staltz** [comment]
Hi @maiermic.
Unfortunately, no, we don't have anything like an Rx TestScheduler, because xstream doesn't have any schedulers.

But you could use `fromDiagram` to aid making input streams in tests, like this: https://github.com/staltz/xstream/blob/master/tests/operator/flatten.ts#L9-L31

**Comment by maiermic** [comment]
Thx, `fromDiagram` is really cool :+1: 

As soon as time of emitted events is relevant and not only order and value, you wish you have virtual time scheduling. Any idea how this can be achieved?

**Comment by staltz** [comment]
There's no other way than using a scheduler. I don't think we'll add schedulers any time soon, but we may add easy conversion from other observables (like from RxJS) to xstream streams, so you could use directly the Rx TestScheduler.

**Comment by maiermic** [comment]
Conversion is acceptable to me to bridge the time till a xstream specific solution is available.
