### ISSUE TITLE
events getting lost upon merge

### ISSUE THREAD

**Issue by ShayMatasaro** [staltz/xstream#96]
The click events in the blow example never  propagate to the parent
https://jsbin.com/dazeha/4/edit?html,js,console,output

 i added debug() in multiple places to rule out a map() bug that i saw previously but still when i merge actions the events disappear ?

 add listener is  emulating a driver and for debugging purposes

is it related to  staltz/xstream#91 ?

**Comment by staltz** [comment]
@ShayMatasaro I think there are too many things that may have a bug in that example. I'm right now working on fixing a bug in Cycle DOM with lists and isolate, it could fix your case too, let's see when I release it.

**Comment by ShayMatasaro** [comment]
@staltz  sounds good, ill wait for your update

**Comment by staltz** [comment]
Try now with Cycle DOM v12.0.1

**Comment by ShayMatasaro** [comment]
just tested 12.0.2 and the issue still exists

**Comment by ntilwalli** [comment]
@ShayMatasaro Your print statement **should** print twice.  `xs.of()` streams emit values synchronously (which are printed via the debug) and complete synchronously which means when the first `addListener` is called the emission happens, and the stream completes... _then_ the `addListener` call in `Cycle.run` happens, which reactivates the stream, which emits all over again and then prints, triggering the printing once again.  I don't see the usage of`xs.merge` anywhere in that code.  Where is the problematic `merge` taking place?

**Comment by ntilwalli** [comment]
If you want to simulate a non-completing stream with `xs.of(...)` you need to `merge` it with `xs.never()`.

**Comment by ShayMatasaro** [comment]
@ntilwalli thanks for looking at the code , i revised it today , here is the correct snapshot with merge 
https://jsbin.com/dazeha/4/edit?html,js,console,output

**Comment by ntilwalli** [comment]
Like Andre said, there's too much that could be going wrong to isolate any specific bug.  Some thoughts:
1) Your functions are named odd.  The `combineDoms` function uses `merge` and the `mergeDoms` function uses `combine`?
2) Your inputs to the component are `xs.of` streams which complete synchronously which means they'll be restarted once per listener which means streams which depend on those will complete as well.  It very well could be that the DOM events are being fed into completed streams or something like that and you'll lose events in that scenario.  You need to `merge` each `xs.of` stream with `xs.never` so as not to deal with completing streams which restart.
3) If you can update the code to use the standard pattern, i.e. each component has its own `intent`, `model` and `view` functions as well as a wrapping `main`, that will help others in debugging.

**Comment by ShayMatasaro** [comment]
@ntilwalli  that was it :+1: 

 the synch streams generated by xs.of() were messing things up , once i merged them with xs.never(), they stopped repeating for each listener and drivers , and the events started flowing properly.

**Comment by ntilwalli** [comment]
Awesome!  This issue can be closed.
