### ISSUE TITLE
FAQ translation of RxJS' withLatestFrom not preserving semantics 

### ISSUE THREAD

**Issue by tlaitinen** [staltz/xstream#97]
The following code 
```javascript
import Rx from 'rxjs/Rx';

const s1 = Rx.Observable.interval(1000).take(3);
const s2 = Rx.Observable.interval(100).take(30);
const s3 = s1.withLatestFrom(s2, (v1,v2) => [v1,v2])
s3.subscribe(function (x) { console.log(x) })
```
outputs 
```
[ 0, 8 ]
[ 1, 18 ]
[ 2, 28 ]
```

According to FAQ, `withLatestFrom` can be expressed in xstream as follows:

```javascript
import xs from 'xstream'

const s1 = xs.periodic(1000).take(3);
const s2 = xs.periodic(100).take(30);
const s3 = s1.map((v1) => s2.map((v2) => [v1,v2])).flatten(); 
s3.addListener({
    next: x => console.log(x),
    error: err => console.error(err),
    complete: () => console.log('completed')
})
```

However, it outputs 30 tuples instead of 3:
```
[ 0, 0 ]
[ 0, 1 ]
[ 0, 2 ]
[ 0, 3 ]
[ 0, 4 ]
[ 0, 5 ]
[ 0, 6 ]
[ 0, 7 ]
[ 0, 8 ]
[ 1, 9 ]
[ 1, 10 ]
[ 1, 11 ]
[ 1, 12 ]
[ 1, 13 ]
[ 1, 14 ]
[ 1, 15 ]
[ 1, 16 ]
[ 1, 17 ]
[ 1, 18 ]
[ 2, 19 ]
[ 2, 20 ]
[ 2, 21 ]
[ 2, 22 ]
[ 2, 23 ]
[ 2, 24 ]
[ 2, 25 ]
[ 2, 26 ]
[ 2, 27 ]
[ 2, 28 ]
[ 2, 29 ]
completed
```

**Comment by ntilwalli** [comment]
Proper `withLatestFrom` translation is:
```
// In rx 4
a$.withLatestFrom(b$)
// In xstream
const bMem$ = b$.remember(); 
a$.map(a => bMem$.take(1).map(b => [a, b]).flatten()
```

**Comment by ntilwalli** [comment]
Yeah, the FAQ should prolly be changed.  In Rx 4, `withLatestFrom` only emits when `a$` has an emission and internally it remembers the updates to `b$` so that when `a$` does emit, it's ready with the latest value, and then it emits that latest value along with `a`.  It does not continue emitting values when `b$` gets further emissions without a new emission from `a$`. In xstream, it continues emitting on changes to the emission from `b$`.   To get that same behavior in xstream you need to do that remembering and taking 1 yourself.

**Comment by ntilwalli** [comment]
Actually, proper `withLatestFrom` in xstream is more like:
```
// In rx 4
a$.withLatestFrom(b$)
// In xstream
const bMem$ = b$.remember(); 
a$.startWith(`throwaway`)
    .map(a => bMem$.take(1).map(b => [a, b]).filter(val => val[0] !== `throwaway`))
    .flatten()
```
The startWith is necessary to activate the `bMem$` at the same time as the `a$` so the first listener for `bMem$`, gets added before `a$` gets it's first output, the filter is needed to disregard the output if `b$` emits first.  The `throwaway` value is arbitrary but should be a value outside the range of values `a$` would normally output so it's okay to filter it.

This is quite not pretty, I wonder if other people can suggest a better approach.

**Comment by Hypnosphi** [comment]
You switched over `s1` and `s2`

**Comment by ntilwalli** [comment]
Agreed, in most cases you don't need full semantic equivalence

**Comment by ntilwalli** [comment]
The latest example code I posted assumes `remember` internally adds a listener to the `b$` implicitly making it active/hot so it can cache values even without external listeners.  If that's not the case, they you'd need to explicitly call `addListener` on `bMem$` yourself to guarantee a listener so values start being cached, and you could then remove the `startWith` and `filter` calls.

**Comment by whitecolor** [comment]
I think `withLastestFrom` should be properly implemented as extra operator

**Comment by ntilwalli** [comment]
Agreed

**Comment by geovanisouza92** [comment]
In fact, it will be
https://gitter.im/staltz/xstream?at=578f1cbc75045f8767085f8d

Em ter, 2 de ago de 2016 11:47, Nikhil Tilwalli <notifications@github.com>
escreveu:

**Comment by staltz** [comment]
Issue #102 is for implementing withLatestFrom as an extra operator, so I think we can close this one.
